- package-lock.json
- package.json
- src/actions/arcActions.ts
- src/actions/web3Actions.ts
- src/reducers/web3Reducer.ts
This gets Arc.js v38 which works-around issues with getting the default account when unlocking Metamask on application startup.
Also calls `InitialSchemesSet` instead of `NewOrg` when getting list of DAOs, to avoid getting corrupt DAOs.
> Handle issues with getting the default account when unlocking Metamask on application startup.

- .gitignore
- package.json
- src/App.spec.tsx
- src/reducers/notificationsReducer.spec.ts
- tslint.json
Changes:
- added `jest` along with other deps, configuration for `jest` is in `package.json["jest"]`.
- two simple tests to make sure it's all working: [`reducers/notificationsReducer.spec.ts`,`App.spec.tsx`].
Commands:
- `npm run test`
- `npm run test:watch` - rerun relevant tests upon file changes.
Jest also generates coverage reports (in `coverage/`), which can be useful.
> add jest for automatic unit testing.

- src/actions/arcActions.ts
- src/actions/notificationsActions.ts
- src/actions/web3Actions.ts
- src/reducers/arcReducer.ts
- src/reducers/notificationsReducer.ts
display notification upon any `REJECTED` actions. 
Reset staking loading animation upon failure.
> Display errors

- src/lib/util.ts
As I said in trello, `ganache-cli` doesn't have a const `networkId`, but arc.js does provide one.
> detect gananche network name

- src/reducers/arcReducer.ts
The lack of `return` in the function inside `update` made the reducer effectively remove the member from the dao, because it was returning undefined.
> fix update tokens/rep bug

- src/components/Proposal/PredictionBox.tsx
This happens because of https://github.com/daostack/arc.js/issues/215. A work-around is possible until there's a new version. But in certain cases it might be solved with a simple UI fix.
- When staking, disable staking on a different prediction than the one already staked on.
- Is there other cases in which this happens?
> Fix 'stuck on pending'

- src/actions/arcActions.ts
- src/components/ViewDao/DaoRedemptionsContainer.tsx
Note: The `revert` I saw was probably because the proposal was not being executed before redemption, fixed at: https://github.com/daostack/alchemy/commit/fe98fac1a634fa579aa6c8cf0f43b98bc7395022
Also posted this issue: https://github.com/daostack/alchemy/issues/76
> Move passed proposals to redeeming

- src/actions/arcActions.ts
- src/lib/util.ts
- src/reducers/operations.ts
Fix how subscriptions to the Arc.js transaction service for Alchemy operations
We now fire two separate callbacks, one before any of the transactions are actually started (onKickoff) and one after each transaction completes (onTransaction).
This allows us to show the first notification at the appropriate time
Handle multi-step operations better, like staking
At beginning show step as  0 of 2, then the operation is complete at 2 of 2
> Fix operation handling

- package-lock.json
- webpack.prod.config.js
Fixes "Invalid number of arguments to Solidity function" with staking.
See https://github.com/ethereum/web3.js/issues/1043 and https://github.com/ethereum/web3.js/issues/1356.
> don't minify BigNumber

- tsconfig.json
including `scripts/populateDAO.ts` in `tsconfig.json` makes typescript output a different directory structure that causes the cache script to fail not finding the file `dist/bg_cache_worker.js`. Note: This was already deployed to production and works successfully.
> Fix build bug causing cache script to fail

- src/components/ViewDao/DaoHeadings.tsx
- src/components/ViewDao/ViewDao.scss
- src/components/ViewDao/ViewDao.scss.d.ts
- src/components/ViewDao/ViewDaoContainer.tsx
This is the fulfillment of a passed Genesis proposal for [DAO-chosen headings in Alchemy](https://docs.google.com/document/d/1g9CGhDRdcPffftwJmmdNa34umhrpudqzR77NW5SOG_U/edit).
From the proposal: 
> Create a prominent space in Alchemy UI where the Genesis DAO can display custom text. This text can be anything the DAO decides: a mission, objectives, an advertisement, and so on. This proposal demonstrates the process by putting in some placeholder text.
Added a small section to the ViewDaoContainer that looks for the latest executed proposal with a title starting with "DAO Heading:" and displays the rest of that proposal's title underneath the header.
_Disclaimer: I'm a beginner coder, so please help me correct my mistakes!_
> Add basic DAO-chosen headings

- README.md
The marketing department would like to add a bit of general comms info to the READMEs of some of our repos. Let us know if this stuff is a no-go for whatever reason.
> Adding comms info to README

- src/components/Proposal/PredictionBox.tsx
- src/components/Proposal/ProposalContainer.tsx
- src/components/Proposal/VoteBox.tsx
Fixes https://github.com/daostack/alchemy/issues/514 as well as trying to stake a pre boosted, expired proposal which causes a transaction revert
Will still need some styling from aaron
> Fix button states

- package-lock.json
- package.json
- src/components/CreateProposal/CreateProposalContainer.tsx
This adds `upstakeNeededToPreBoost` and `downStakeNeededToQueue` to the Proposal object from the client.
note that this numbers can be negative!
> upgrade client to 51

- src/reducers/arcReducer.ts
Basically if a proposal was boosted then unboosted we were hiding it when it reached what was previously the end of its pre boosting time period.
Fixes https://github.com/daostack/alchemy/issues/603
> Don’t hide some unboosted proposals

- src/components/Proposal/ActionButton.tsx
- src/lib/util.ts
This was broken before, though probably to effecting anything since we are now redeeming CR rewards on proposal execute.
Also a little fix to correctly show external token symbols when known
> Dont check DAO external token balance when looking for proposal rewards

- src/components/CreateProposal/SchemeForms/CreateContributionRewardProposal.tsx
Fix #734
The options used the wring name. The client expected the key to be `externalTokenAddress`, while Alchemy sent `externalToken`.
https://github.com/daostack/client/blob/master/src/proposal.ts#L199
> Fix external token address bug

- src/components/Account/AccountProfileContainer.tsx
We weren’t checking if user had enabled MetaMask. And needed to fix the from param to the .send call
FIxes https://daostack.tpondemand.com/RestUI/Board.aspx#page=board/5209716961861964288&appConfig=eyJhY2lkIjoiQjgzMTMzNDczNzlCMUI5QUE0RUE1NUVEOUQyQzdFNkIifQ==&boardPopup=bug/1020/silent
> Fix account profile saving again

- src/components/Proposal/ActionButton.tsx
- src/components/Proposal/Predictions/BoostAmount.tsx
- src/components/Proposal/Predictions/PredictionButtons.scss
- src/components/Proposal/Predictions/PredictionButtons.tsx
- src/lib/util.ts
Show GEN to preboost amounts and preboost button correctly
Only when over the threshold, not at the threshold
Use > symbols instead of + symbols to indicate token amounts that are more than the number shown
> [WIP] 1041 upstakes to preboost

- src/components/Shared/SocialShareModal.scss
- src/layouts/App.scss
- src/layouts/AppContainer.tsx
Addresses the vertical positioning issue with this popup and all others (Voters and PreTransaction).
See https://daostack.tpondemand.com/RestUI/Board.aspx#page=board/5209716961861964288&appConfig=eyJhY2lkIjoiQjgzMTMzNDczNzlCMUI5QUE0RUE1NUVEOUQyQzdFNkIifQ==&boardPopup=userstory/839/silent
And https://github.com/daostack/alchemy/issues/1041
Note this does not fully resolve the latter github issue, as that includes horizontal clipping and changing the mobile layouts of the other popups.
> fix vertical modal positioning on mobile

- CHANGELOG.md
- src/components/Proposal/ProposalDetailsPage.tsx
Resolves: https://daostack.tpondemand.com/RestUI/Board.aspx#page=board/5209716961861964288&appConfig=eyJhY2lkIjoiQjgzMTMzNDczNzlCMUI5QUE0RUE1NUVEOUQyQzdFNkIifQ==&boardPopup=userstory/1565/silent
> Links in proposal description should open in a new tab

- CHANGELOG.md
- src/arc.ts
Resolves: https://daostack.tpondemand.com/RestUI/Board.aspx#page=board/5209716961861964288&appConfig=eyJhY2lkIjoiQjgzMTMzNDczNzlCMUI5QUE0RUE1NUVEOUQyQzdFNkIifQ==&boardPopup=bug/1543/silent
STEPS:
1. do a transaction using any MetaMask account
2. change the current account in MetaMask
3. try a transaction
RESULT: Nothing happens except an error in the console: > Error: WalletMiddleware - Invalid "from" address.
The PR invokes `InitializeArc` appropriately to address this use case.
> Can't send transaction after changing account

- CHANGELOG.md
- src/components/Daos/DaoCard.tsx
- src/components/Daos/Daos.scss
Resolves: https://daostack.tpondemand.com/RestUI/Board.aspx#page=board/5209716961861964288&appConfig=eyJhY2lkIjoiQjgzMTMzNDczNzlCMUI5QUE0RUE1NUVEOUQyQzdFNkIifQ==&boardPopup=userstory/1662/silent
Compat design for DAO cards on mobile.  "The biggest change is the vertical paddings and total height of a dao card (to have more DAOs show on one screen simultaneously)…"
I also cleaned up the layout of the statistics at certain page widths and fixed their fonts at mobile sizes, which weren't being set properly.
> Compat design for DAO cards on mobile

- CHANGELOG.md
- src/arc.ts
- src/components/Account/AccountProfilePage.tsx
- src/components/Proposal/ActionButton.tsx
- src/components/Proposal/Create/SchemeForms/CreateContributionRewardProposal.tsx
- src/components/Proposal/Create/SchemeForms/CreateKnownGenericSchemeProposal.tsx
- src/components/Proposal/Create/SchemeForms/CreateSchemeRegistrarProposal.tsx
- src/components/Proposal/Create/SchemeForms/CreateUnknownGenericSchemeProposal.tsx
- src/components/Proposal/Staking/StakeButtons.tsx
- src/components/Proposal/Voting/VoteBreakdown.tsx
- src/components/Proposal/Voting/VoteButtons.tsx
- src/components/Redemptions/RedemptionsMenu.tsx
- src/components/Redemptions/RedemptionsPage.tsx
- src/components/Scheme/ReputationFromToken.tsx
- src/components/Scheme/SchemeContainer.tsx
- src/components/Scheme/SchemeProposalsPage.tsx
- src/components/Shared/PreTransactionModal.tsx
- src/layouts/AppContainer.tsx
- src/layouts/Header.tsx
Resolves: https://daostack.tpondemand.com/RestUI/Board.aspx#page=board/5209716961861964288&appConfig=eyJhY2lkIjoiQjgzMTMzNDczNzlCMUI5QUE0RUE1NUVEOUQyQzdFNkIifQ==&boardPopup=bug/1648/silent
This completes the second part of the ticket:  "The logic should be the same regardless of how the user chooses to connect / login / make an action (e.g. stake when not connected)…  If we have a cached provider then use it, if no cached provider - show the web3connect dialogue…"
- calls to enableWeb3ProviderAndWarn now call enableWalletProvider instead
- unlike the old enableWeb3ProviderAndWarn, enableWalletProvider always looks to the cache first
- **Further note**  I am proposing here to issue a notification when the user is automatically connected (but not when doing it manually through the Connect …
> Cached provider should always be used when possible

- src/components/Account/Reputation.tsx
For dOrg, having the amount the agent is requested readily available is needed for us to properly audit payments. Currently Alchemy only shows the percentage and the total REP in the DAO.
Closes https://github.com/daostack/alchemy/issues/979
> Display Redeemable REP On-Hover

- src/components/Dao/Dao.scss
- src/components/Dao/DaoDiscussionPage.tsx
- src/components/Dao/DaoSidebar.tsx
Resolves: https://daostack.tpondemand.com/RestUI/Board.aspx#page=board/5209716961861964288&appConfig=eyJhY2lkIjoiQjgzMTMzNDczNzlCMUI5QUE0RUE1NUVEOUQyQzdFNkIifQ==&boardPopup=userstory/1649/silent
Show red dot next to "DAO Wall" in sidebar when there are unread messages.
**Important**:  To use the Disqus API I had to create an "[API Application](https://help.disqus.com/en/articles/1717083-how-to-create-an-api-application)" in Disqus.  I have enabled access to any domain for debugging until this PR is merged.  Access is limited to "readonly" in any case.
**Note** API access is throttled without upgrading to a "Pro" subscription, which we already have.  Yet it is reporting that we have a limit of 1000 queries per hour.
Here is the API Application config: …
> Feedback on whether there are unread Discus posts on DAO Wall

- src/components/Shared/SocialShareModal.tsx
Resolves: https://daostack.tpondemand.com/RestUI/Board.aspx#page=board/5209716961861964288&appConfig=eyJhY2lkIjoiQjgzMTMzNDczNzlCMUI5QUE0RUE1NUVEOUQyQzdFNkIifQ==&boardPopup=userstory/1708/silent
The ticket didn't mention the other social networks we share to, but I went ahead and added "DAOstack" (without the "@") to those.
> Reference "@DAOstack" in Twitter sharing message

- src/components/Proposal/Staking/StakeButtons.scss
- src/components/Proposal/Voting/VoteButtons.scss
Resolves: https://daostack.tpondemand.com/RestUI/Board.aspx#page=board/4789434231796866533&appConfig=eyJhY2lkIjoiMEFGRDcyNjIyOTgzRjFFMkMwRjIwMDBCNzA0QjRGMzQifQ==&boardPopup=bug/1483/silent
Resolves: https://daostack.tpondemand.com/RestUI/Board.aspx#page=board/5209716961861964288&appConfig=eyJhY2lkIjoiQjgzMTMzNDczNzlCMUI5QUE0RUE1NUVEOUQyQzdFNkIifQ==&boardPopup=bug/1658/silent
After much going back and forth, I decided not to remove the gaps in the staking and voting buttons.  I feel that the gap makes it easier to know these are two buttons.  And I have run across precendent for this design elsewhere on the web.
But again finding that the font sizes are different in voting versus staking buttons, I made them the same, opting to choose the larger size in each case (the topic of [this …
> equalize button text font sizes

- src/actions/arcActions.ts
- src/actions/web3Actions.ts
- src/components/Proposal/Staking/StakeButtons.tsx
- src/layouts/AppContainer.tsx
- src/reducers/web3Reducer.ts
Resolves: https://daostack.tpondemand.com/RestUI/Board.aspx#page=board/5209716961861964288&appConfig=eyJhY2lkIjoiQjgzMTMzNDczNzlCMUI5QUE0RUE1NUVEOUQyQzdFNkIifQ==&boardPopup=bug/1546/silent
Resolves: https://github.com/daostack/alchemy/issues/1073
* Transaction notifications are now shown when enabling predictions, just like other txs.
* Removed some unused code
> show notifs on Enable Predictions

- src/components/Proposal/ProposalStatus.scss
- src/components/Proposal/ProposalStatus.tsx
Resolves: https://daostack.tpondemand.com/RestUI/Board.aspx#page=board/5209716961861964288&appConfig=eyJhY2lkIjoiQjgzMTMzNDczNzlCMUI5QUE0RUE1NUVEOUQyQzdFNkIifQ==&boardPopup=bug/1731/silent
Looks like Boosted, but displays "Quiet Ending"
> display quiet ending status

- CHANGELOG.md
- src/layouts/App.scss
- src/layouts/Header.tsx
Resolves: https://daostack.tpondemand.com/RestUI/Board.aspx#page=board/5209716961861964288&appConfig=eyJhY2lkIjoiQjgzMTMzNDczNzlCMUI5QUE0RUE1NUVEOUQyQzdFNkIifQ==&boardPopup=bug/1748/silent
Solution is to drop the menu down rather than from the side.  I think this is better UX anyway, since the trigger for the menu is at the top, not on the right.
> nervous account menu: drop down instead of left

- CHANGELOG.md
- src/assets/styles/_rc-tooltip.scss
- src/components/Proposal/ActionButton.tsx
- src/components/Proposal/RedemptionsTip.tsx
- src/components/Shared/PreTransactionModal.scss
- src/components/Shared/PreTransactionModal.tsx
- src/lib/util.ts
Resolves: https://daostack.tpondemand.com/RestUI/Board.aspx#page=board/5209716961861964288&appConfig=eyJhY2lkIjoiQjgzMTMzNDczNzlCMUI5QUE0RUE1NUVEOUQyQzdFNkIifQ==&boardPopup=bug/1312/silent
I think the UX is a little weird in the case when some redemptions are possible and some aren't.  In that case the Redeem button will not disappear after redeeming.  All that changes is the tooltip over the Redeem button (perhaps only after refreshing the page) and when clicking the Redeem button _again_ you get a failure notification (until the DAO is able to pay out).  I think it would be better if we give the user a warning notification after running Redeem the first time to inform the user that the Redeem did not completely succeed.  @jellegerbrandy 
* shows failure notification when the user tries …
> Block redeem when can't be paid

- src/arc.ts
- src/components/Account/AccountProfilePage.tsx
- src/components/Account/OAuthLogin.tsx
- src/components/Dao/DaoContainer.tsx
- src/components/Dao/DaoSidebar.tsx
- src/components/Daos/DaoCard.tsx
- src/components/Notification/MinimizedNotifications.tsx
- src/components/Proposal/ActionButton.tsx
- src/components/Proposal/Create/SchemeForms/CreateContributionRewardProposal.tsx
- src/components/Proposal/Create/SchemeForms/CreateKnownGenericSchemeProposal.tsx
- src/components/Proposal/Create/SchemeForms/CreateSchemeRegistrarProposal.tsx
- src/components/Proposal/Create/SchemeForms/CreateUnknownGenericSchemeProposal.tsx
- src/components/Proposal/Create/SchemeForms/MarkdownField.tsx
- src/components/Proposal/Create/SchemeForms/TagsSelector.tsx
- src/components/Proposal/ProposalSummary/ProposalSummaryKnownGenericScheme.tsx
- src/components/Proposal/ProposalSummary/ProposalSummarySchemeRegistrar.tsx
- src/components/Proposal/Staking/StakeButtons.tsx
- src/components/Proposal/Voting/VoteButtons.tsx
- src/components/Redemptions/RedemptionsButton.tsx
- src/components/Redemptions/RedemptionsMenu.tsx
- src/components/Redemptions/RedemptionsPage.tsx
- src/components/Scheme/ReputationFromToken.tsx
- src/components/Scheme/SchemeContainer.tsx
- src/components/Shared/PreTransactionModal.tsx
- src/layouts/AppContainer.tsx
- src/layouts/Header.tsx
- src/lib/util.ts
This is in an effort to minimize spurious react component rendering by removing most of the uses of arrow and .bind functions  in `render`. 
Down to only 11 lint warnings.
But I don't honestly see any significant performance improvements.
> remove most arrow function and .bind lint errors

- CHANGELOG.md
- src/components/Dao/DaoContainer.tsx
- src/components/Shared/withSubscription.tsx
Resolves:
https://daostack.tpondemand.com/RestUI/Board.aspx#page=board/5209716961861964288&appConfig=eyJhY2lkIjoiQjgzMTMzNDczNzlCMUI5QUE0RUE1NUVEOUQyQzdFNkIifQ==&boardPopup=bug/1802/silent
Goes to error page on non-existent DAOs
**Note** that the code that handles non-existent DAOs has the potential to trap other types of exceptions and redirect to the error page.
> error page on unregistered DAOs

- CHANGELOG.md
- src/components/Proposal/ActionButton.scss
- src/components/Proposal/ActionButton.tsx
- src/components/Proposal/RedemptionsTip.tsx
- src/components/Redemptions/RedemptionsPage.scss
- src/components/Redemptions/RedemptionsPage.tsx
- src/components/Shared/PreTransactionModal.scss
- test/integration/rewards.ts
- test/integration/utils.ts
Resolves: 
https://daostack.tpondemand.com/RestUI/Board.aspx#page=board/5209716961861964288&appConfig=eyJhY2lkIjoiQjgzMTMzNDczNzlCMUI5QUE0RUE1NUVEOUQyQzdFNkIifQ==&boardPopup=bug/1817/silent
(Should not say insufficient resources for just redeeming rep)
and parts of:
https://daostack.tpondemand.com/RestUI/Board.aspx#page=board/5209716961861964288&appConfig=eyJhY2lkIjoiQjgzMTMzNDczNzlCMUI5QUE0RUE1NUVEOUQyQzdFNkIifQ==&boardPopup=bug/1804/silent
Of the latter:
* disables Redeem button if nothing can be redeemed due to lack of funds.  Makes it look disabled when disabled.
* corrects logic governing when the Redeem button should be visible
* corrects logic for when Redeem button text should say "For Beneficiary"
Also:
* a few helpful changes to the redemptions tooltip text and the style of the …
> fix several issues with redemption tooltip and action button

- CHANGELOG.md
- src/components/Account/AccountProfilePage.tsx
- src/components/Dao/DaoContainer.tsx
- src/components/Dao/DaoHistoryPage.tsx
- src/components/Dao/DaoMember.tsx
- src/components/Dao/DaoMembersPage.tsx
- src/components/Dao/DaoSchemesPage.tsx
- src/components/Proposal/ProposalCard.tsx
- src/components/Proposal/ProposalData.tsx
- src/components/Proposal/ProposalDetailsPage.tsx
- src/components/Redemptions/RedemptionsMenu.tsx
- src/components/Scheme/SchemeContainer.tsx
- src/components/Scheme/SchemeInfoPage.tsx
- src/components/Scheme/SchemeProposalsPage.tsx
- src/layouts/Header.tsx
Resolves:  https://github.com/daostack/alchemy/issues/1171
Resolves: https://daostack.tpondemand.com/RestUI/Board.aspx#page=board/5209716961861964288&appConfig=eyJhY2lkIjoiQjgzMTMzNDczNzlCMUI5QUE0RUE1NUVEOUQyQzdFNkIifQ==&boardPopup=bug/1749/silent
* Fixes the 125% issue in the original use case as well as everywhere else where the reputation percentage is displayed.  Accomplished this by subscribing to changes in the DAOstate whereever `DAOstate.reputationTotalSupply` is used.
* cleans up some places where the dao state is being redundantly created.
**Note** there still remain some places that create their own instances of DAO and DAOstate.  These are characterized as being code that is not under `DAOContainer`, for example the app header, redemptions menu and account profile code.  So …
> update DAO total reputation supply when it changes

- src/components/Proposal/ActionButton.tsx
Fixes:  Due to a recent code change, certain handlings of missing tokens is taking us to the error page when visiting the Scheme Proposals page, and possibly other pages, against ganache and on staging.
> suppress exception on bad tokens

- src/components/Proposal/ProposalData.tsx
- src/components/Proposal/ProposalDetailsPage.tsx
- src/settings.ts
Resolves: https://daostack.tpondemand.com/RestUI/Board.aspx#page=board/5209716961861964288&appConfig=eyJhY2lkIjoiQjgzMTMzNDczNzlCMUI5QUE0RUE1NUVEOUQyQzdFNkIifQ==&boardPopup=bug/1756/silent
This fixes not just voting feedback, but also staking and anything related to redemptions.
I feel weird about adding subscriptions, but don't know another way to address this unless we can do a fetchAllData on the proposal itself and subscribe directly to it.  But that makes me feel weird too, so will defer to @jellegerbrandy on the best way to do this.
> add subscriptions for votes, stakes and rewards

- src/components/Notification/Notification.scss
- src/layouts/App.scss
Resolves: https://daostack.tpondemand.com/RestUI/Board.aspx#page=board/5209716961861964288&appConfig=eyJhY2lkIjoiQjgzMTMzNDczNzlCMUI5QUE0RUE1NUVEOUQyQzdFNkIifQ==&boardPopup=bug/1564/silent
Now provides better visibility on all pages, including being better on DAO-related pages.
Looks like this:
On home (DAOs) page:
On DAO page (with DaoSideBar):
> better position notifs on all pages

- src/components/Scheme/SchemeInfoPage.tsx
Fixes https://github.com/daostack/alchemy/issues/1282
and https://github.com/daostack/alchemy/issues/1290
> Actually fix representation of durations in Plugin info page

- src/actions/arcActions.ts
- src/components/Scheme/ReputationFromToken.tsx
Also attempt to set to 0 after redeem succeeds, but hard to do this with current client library, see https://github.com/daostack/client/issues/412
Also disable redeem buttons when 0 rep to redeem
Fixes https://github.com/daostack/alchemy/issues/1348 & https://github.com/daostack/alchemy/issues/1319
> Update # rep to redeem from tokens when switching account

- src/components/Proposal/Create/SchemeForms/CreateUnknownGenericSchemeProposal.tsx
to allow character `f`
see #1454
> Fixing the hex byte pattern regex in Generic Scheme Proposal Form

- package-lock.json
- package.json
The fix needed was to upgrade the `web3` dependency DAOcreator's Lib uses to 1.2.4. The old version included a `preInstall` script that used the `rm` unix command.
> Fix Windows Install

- src/components/Dao/DaoHistoryPage.tsx
Works around https://github.com/daostack/alchemy/issues/1510
Simply hides the proposals that are crashing the History page.
> workaround Schemeless Proposals

- src/components/Daos/DaosPage.tsx
To make sure we find all DAOs even if they have not yet been loaded on the client yet
Also only search after more than 2 characters typed in box
TODO: search different cases of the search string?
Fixes: https://github.com/daostack/alchemy/issues/1484
> When searching DAOs check server not just current ones in client

- CHANGELOG.md
- package-lock.json
- package.json
- webpack.prod.config.js
Upgrades to 11.15.0, the highest version that builds.  I spent a lot of time trying to get 12.x to work, without ultimate success.  I think 11.15.0 accomplishes the spirit of the request.
Removes the `cheap` devtool in the prod webpack config and still builds.
> upgrade node version

- src/components/Proposal/ProposalSummary/ProposalSummaryCO2ken.tsx
- src/components/Proposal/ProposalSummary/ProposalSummaryKnownGenericScheme.tsx
- src/genericSchemeRegistry/index.ts
- src/genericSchemeRegistry/schemes/CO2ken.json
These changes have been made under the guidance of Jordan Ellis (@dOrgJelli).
We have deployed a new DAO on DAOStack called CarbonDAO (currently on Rinkeby at `0xc9a37828f16649fb3f578e3cc4968fbd46c301ac`).
This commit provides a custom UI for our custom `CO2ken.sol` contract which can be found at https://github.com/CO2ken/CO2ken/tree/master/Contracts (Rinkeby address: `0x93Ec2167Da2A83fbBE61567F67F71750C13B9C09`).
Our DAO tokenizes carbon offsets based on certificates purchased from carbon offset retailers.
When minting new tokens, a hash to the certificates stored on IPFS has to be provided. 
To be able to include a link to these certificates in a new proposal we had to change the generic scheme proposal UI.
You can read more about the project at:
- …
> Add CO2ken scheme and corresponding proposal summary custom UI

- src/components/Proposal/ProposalSummary/ProposalSummaryCO2ken.tsx
- src/genericSchemeRegistry/schemes/CO2ken.json
Altered the `ProposalSummaryCO2ken.tsx` to account for the changes in the
`CO2ken.json` scheme and correctly display decimal values.
Couldn't test it locally yet because it wouldn't compile properly due to unrelated issues:
```
ERROR in ./src/arc.ts
Module not found: Error: Can't resolve 'web3modal' in '/Users/raphaelbenoit/Documents/*BRAIN*/Projects/EthLondon/alchemy/src'
@ ./src/arc.ts 17:20-40
@ ./src/App.tsx
@ ./src/index.tsx
@ multi react-hot-loader/patch webpack-dev-server/client?http://127.0.0.1:3000 webpack/hot/only-dev-server ./src/index.tsx
ERROR in [at-loader] ./src/arc.ts:4:31 
TS2307: Cannot find module 'web3modal/lib/helpers/types'.
ERROR in [at-loader] ./src/arc.ts:7:44 
TS2307: Cannot find module 'web3modal'.
ERROR in [at-loader] ./src/arc.ts:398:80 
TS2339: Property …
```
> [UNTESTED] Changed the CO2ken scheme to process decimal values of input fields

- src/settings.ts
our build process was changed slightly
this import still works if you enable esModuleInterop: true in your tsconfig but there are other issues if you do that in the alchemy repo. 
Instead, if you import it via require, it just works.
Ran this via npm run start-prod and was able to see Torus in the Web3Modal modal, and also login successfully.
> Import torus using require

- src/layouts/SidebarMenu.scss
- src/layouts/SidebarMenu.tsx
Fix overlap of tokens on bottom links: https://github.com/daostack/alchemy/issues/1505
Make sure bottom links are always visible: https://github.com/daostack/alchemy/issues/1548
Add scrolling to mobile menu if necessary
> Fix display of sidebar menu

- src/components/Notification/Notification.tsx
Fixes a weird "bug" in the Biconomy PR
> Don't show weird confirmation popups when using the "Pending" notification type

- src/subgraph_endpoints.json
due to a [bug]( https://github.com/daostack/subgraph/pull/538) in subgraph
- isRegistered flag is false if scheme is unregistered and then re registered. -- cause alchemy to not display the scheme
> Update to use subgraph v39_4 

- src/components/Scheme/Scheme.scss
- src/components/Scheme/SchemeContainer.tsx
- src/components/Scheme/SchemeInfo.scss
- src/components/Scheme/SchemeInfoPage.tsx
- src/components/Scheme/SchemeProposals.scss
- src/components/Scheme/SchemeProposalsPage.tsx
Resolves: https://github.com/daostack/alchemy/issues/1674
- This moves the code for the New Proposal and Edit Plugin buttons into the components where they belong, instead of hacking them from the wrong components.
- The appearance of the two buttons is now consistent with the appearance of a similar button:  Edit Plugin on the Proposal Plugins page
- I removed the name of the plugin from the "New Proposal" button because the button is harder to layout when it becomes very wide, and the name is redundant.
- responsive behavior is better than it was, I think, but still not great
There are more notes in the ticket this fixes.
Potentially affected parts, to test:
- the SchemeContainer page for any scheme, (url: /dao/:daoAvatarAddress/scheme/:schemeId) for any scheme, not neglecting special …
> refactor and fix the layout of New Proposal button

- src/genericSchemeRegistry/schemes/ENSPublicResolver.json
input param type should be "address" not "string".
- When using ensPublicResolver generic scheme , calling setAddr produce wrong encoded abi . due to bug in the abi set for this function. 
- This cause the executed generic call proposal to revert at the ENS side. The proposal will look in alchemy as if it passed though.
> fix ensPublicResolver setAddr encoding

- src/components/Proposal/RedemptionsString.scss
- src/components/Proposal/RedemptionsString.tsx
Resolves: https://github.com/daostack/alchemy/issues/1588
There were significant issues here.  Both GEN and reputation numbers were going to be off in multiple scenarios.
I was compelled to clean up a little display code in the process, as it was written in a way that was difficult to evaluate for correctness.
The part of the UI that is fixed is here:
> fix redemption numbers in menu

- src/actions/uiActions.ts
- src/components/Dao/DaoLandingPage.scss
- src/components/Dao/DaoLandingPage.tsx
- src/components/Shared/ModalPopup.tsx
- src/components/Shared/SimpleMessagePopup.scss
- src/components/Shared/SimpleMessagePopup.tsx
- src/layouts/AppContainer.tsx
- src/lib/util.ts
- src/reducers/uiReducer.ts
Replaces any need for `alert`.  Motivated by the Biconomy PR.
DaoLandingPage is now using it, thus simplifying the code in that component.
DAOCreator should be made to use it: 
https://github.com/dOrgTech/DAOcreator/issues/502#issuecomment-634805595
> add simple message popup

- src/components/Shared/PreTransactionModal.scss
**Note**
- I fixed the issue only by changing styling.
- Tested on Chrome, Firefox and Brave browsers.
- If this issue will pop up again I'll make a more robust fix with the template itself and not only with CSS.
- I also checked the error message itself and not only the "GEN" text and it's fine, although I saw in previous discussions that others had problems with this.
> Fix UI issue in staking modal

- src/components/Proposal/Create/PluginForms/PluginInitializeFields.tsx
Added address validation to 'Custom Contract To Call' field when creating a new proposal with 'GenricScheme' plugin.
> Added validation to Custom Contract To Call field

- src/components/Proposal/ProposalSummary/ProposalSummary.scss
- src/components/Proposal/ProposalSummary/ProposalSummaryKnownGenericScheme.tsx
- src/components/Proposal/ProposalSummary/ProposalSummaryUnknownGenericScheme.tsx
Resolves: https://github.com/daostack/alchemy/issues/1856
- truncates the callData value and adds CopyToClipboard button
- makes contract address fully visible (consistent with unknown schemes)
- makes a few needed cosmetic improvements consistent with other proposal details pages
- makes the etherscan link open safely, and in a new tab
> handle wide GenericScheme calldata

- test/integration/utils.ts
- `LATEST_ARC_VERSION` is now fetched from `@daostack/test-env-experimental/package.json`
- Subgraph endpoints are now fetched from `subgraph_endpoints.json`
> Automate params in test/integration/utils

- src/components/Shared/PreTransactionModal.scss
- src/components/Shared/PreTransactionModal.tsx
Resolves: https://github.com/daostack/alchemy/issues/1794
Only resolves the insufficient GEN error message layout, making sure that, whether or not we can reproduce it now, it can't possibly happen again, and cleaning up the code in the process.
The GEN label error (https://github.com/daostack/alchemy/issues/1629#issuecomment-637967166) is not reproducible.
> fix insufficient GEN error message layout

- src/components/Proposal/RedemptionsTip.scss
- src/components/Proposal/RedemptionsTip.tsx
- src/components/Shared/PreTransactionModal.scss
- src/components/Shared/PreTransactionModal.tsx
Resolves: https://github.com/daostack/alchemy/issues/1742
Also:
- creates RedemptionsTip.scss maintain assurance that changes to PreTransactionModal.scss will not affect anything else
- cleans up appearance of the your GEN balance related text
> clean up PreTransactionModal on mobile

- src/components/Dao/DaoPluginsPage.tsx
- src/components/Plugin/PluginContainer.tsx
- src/components/Proposal/Create/PluginForms/CreatePluginManagerProposal.tsx
- src/lib/pluginUtils.ts
It's not possible just to change the names of the plugins since the names themselves are used in more places not just as display names but as dom objects IDs, keys and more.
Instead, I created a new object called: `PLUGINS_UI_NAMES`. Here we can give the display name to each plugin without affecting the IDs, keys and more.
> added plugins UI names

- src/arc.ts
- src/lib/util.ts
Resolves: https://github.com/daostack/alchemy/issues/1828
For the full set of changes and recommendations from MetaMask, see: https://medium.com/metamask/breaking-changes-to-the-metamask-inpage-provider-b4dde069dd0a
Latest status on these changes: https://github.com/MetaMask/metamask-extension/issues/8077#issuecomment-622191567. The changes have not yet taken effect.
This PR is reducing our exposure to window.web3 in general, preferring to use our version of preference, though frankly there wasn't much exposure to eliminate. Just two cases are affected by these changes:
1. when using ganache and both injected windows.web3 and injected windows.ethereum are absent, the choice whether to instantiate our own Web3. We now only look at whether an injected windows.ethereum is absent. So even if …
> prepare for MetaMask ceasing to inject web3

- package-lock.json
- package.json
- src/components/DaoCreator/index.tsx
I added an example on how you should set the URL via props. Now you can, based on the `targetedNetwork`, define where you want to redirect the user when they create a new DAO.
Note: The props just needs the domain (like in the example I did), the rest is handled by daocreator, you can check the code here: https://github.com/dOrgTech/DAOcreator/blob/issue-509-dynamic_link_on_deployment/packages/ui_v2/src/components/commonV2/dao/Migrator/DeployButton.tsx#L452
> Updating daocreator experimental package to set redirect link from alchemy

- src/layouts/Header.tsx
Resolves: https://github.com/daostack/alchemy/issues/1837
I'm not sure why this was not needed in 1.0, but I have a feeling in 1.0 it was more of an intermittent bug, not frequent enough to motivate us to look into it.
> eliminate forceUpdate in Header

- .github/ISSUE_TEMPLATE/bug_report.md
- src/layouts/Header.tsx
- typings/build.d.ts
- webpack.base.config.js
Resolves: https://github.com/daostack/alchemy/issues/1900https://github.com/daostack/alchemy/issues/1900
* puts the version number in a new tooltip over Alchemy icon in the header
* removes the existing TrainingTooltip that was obsolete and incorrect
* obtains the version number using https from github in the package.json of the master-2 branch
* note that unique patch versions might not be reflected in the master branch
* if desired, this could be made to pull the version from dev-2 for staging/review apps
* adds instructions on using the version in the github bug template
* should we do this for Alchemy 1.0 too?  @orenyodfat
> expose alchemy version number

- src/components/Plugin/ContributionRewardExtRewarders/Competition/utils.ts
- src/components/Proposal/Voting/VoteButtons.tsx
- src/lib/proposalHelpers.ts
- src/lib/proposalUtils.ts
- src/lib/util.ts
Resolves: https://github.com/daostack/alchemy/issues/1984
* Adds `safeMoment`.
* a couple other tweaks to attempt to ensure we're safe from any changes to arc.js wrt datetime typing
* where Competition computes its status with respect to its workflow
* where the vote buttons compute whether the proposal was created before the account had rep in the DAO
> handle all arc.js datetime types

- src/assets/locales/en/translation.json
- src/components/Proposal/ProposalSummary/ProposalSummaryCO2ken.tsx
- src/components/Proposal/ProposalSummary/ProposalSummaryDutchX.tsx
- src/components/Proposal/ProposalSummary/ProposalSummaryKnownGenericPlugin.tsx
- src/components/Proposal/ProposalSummary/ProposalSummaryNFTManager.tsx
- src/components/Proposal/ProposalSummary/ProposalSummaryStandardBounties.tsx
Fixes https://github.com/daostack/alchemy/issues/2021 for 2.0.
> add genericscheme callData raw data to the proposal details view

- CHANGELOG.md
- data/tokens.json
- package-lock.json
- package.json
Resolves: https://github.com/daostack/alchemy/issues/2065
Same fix applies to NEC
I'm not wild about this because it doesn't address the fact that someone has to remember/document that these tokens must always be submitted in lowercase.
> Fix dxd token display

- src/components/Proposal/ProposalCard.scss
- src/components/Proposal/ProposalCard.tsx
resolves: https://github.com/daostack/alchemy/issues/2076
Removed redundant code:
`<Link to={"/dao/" + daoState.address + "/proposal/" + proposal.id}>`
Note: GitHub shows many changes because I had to indent the code after wrapping the whole proposal card component in a `<Link>` component. To see the changes in a better way please use **Hide whitespace changes** option.
> Fix issue when a proposal card is not always clickable

- src/components/Daos/DaosPage.tsx
resolves: https://github.com/daostack/alchemy/issues/2088
Minor adjustments due to changes in DAOs balances service that now returns balances only for registered DAOs.
This PR requires https://github.com/daostack/daos-balances/pull/4
> Minor adjustments due to changes in DAOs balances service

- CHANGELOG.md
- data/tokens.json
- docker-compose.yml
- package-lock.json
- package.json
- src/components/Proposal/ProposalDetails.scss
- src/components/Proposal/ProposalDetailsPage.tsx
- src/genericSchemeRegistry/schemes/ENSRegistry.json
- src/genericSchemeRegistry/schemes/RegistryLookup.json
- src/lib/util.ts
- src/subgraph_endpoints.json
- test/integration/proposal-competition.ts
- test/integration/wdio.conf.js
> Release 0.10.15

- src/components/Proposal/Staking/StakeButtons.scss
resolves: https://github.com/daostack/alchemy/issues/2148
Robust styles to the Enable Predictions button to look good on both Windows and Mac.
> Fix Enable Prediction button text overflows

- src/assets/locales/en/translation.json
- src/components/Proposal/Create/CreateProposal.scss
- src/components/Proposal/Create/PluginForms/PluginInitializeFields.tsx
resolves: https://github.com/daostack/alchemy/issues/2122
Now it's clear and easy to distinguish between Add and Remove params.
and
> Added fieldsets in Plugin Manager ---> Plugin Registrar 

- src/components/Plugin/PluginInfoPage.tsx
- src/components/Proposal/ProposalSummary/ProposalSummary.scss
- src/components/Proposal/ProposalSummary/ProposalSummaryPluginManager.tsx
resolves: https://github.com/daostack/alchemy/issues/2165
resolves: https://github.com/daostack/alchemy/issues/2166
- `renderGpParams` function is now exported from `PluginInfoPage.tsx`
- Plugin Manager Proposal Summary Page is now using grids instead of table and uses `renderGpParams` to render it's GP params.
- Replace Plugin title: the plugin title to be replaced is removed
- Fetching the plugin name from the known `PLUGIN_NAMES` object
> Update condition to support Add and Replace plugin

- src/components/Plugin/ContributionRewardExtRewarders/Competition/List.tsx
- src/lib/pluginUtils.ts
resolves: https://github.com/daostack/alchemy/issues/2168
This happens because only Apollo `watchQuery` function accepts `pollInterval` parameter and here we call Apollo `query` function (in arc.js) with `pollInterval` - and that’s why it’s crashes.
**Note:** Maybe we need to limit the option of sending `apolloQueryOptions` / `polling` to a `sendQuery` function in arc.js
> Fix competition tab crash ; Fix compitition plugin ugly name

- src/assets/locales/en/translation.json
- src/components/Proposal/Create/PluginForms/CreateUnknownGenericPluginProposal.tsx
resolves: https://github.com/daostack/alchemy/issues/2183
> Different message when no write methods found in ABI

- src/components/Proposal/ProposalData.tsx
- src/components/Redemptions/RedemptionsMenu.tsx
- src/layouts/SidebarMenu.tsx
Needed because there are some edge cases where the subgraph cannot represent the real balance of a dao.
e.g transferring funds via xdai bridge directly to the dao ..(this will. not trigger a dao event.
> dao balance not from subgraph

- src/arc.ts
- src/components/Shared/withSubscription.tsx
Due to the way Apollo Client works, when a GraphQL or a network error occurs it fails and terminates the observable including the polling, then Alchemy crashes. This is the simplest and cleanest solution to address this issue without changing anything in arc.js.
This is a known bug in Apollo Client `watchQuery` when polling, and looks like the only way to avoid this is to recreate the polling when such an error occurs.
> Ignore network and GraphQL errors

- src/components/Proposal/ActionButton.tsx
The condition is missing brackets, so if it's a `genericScheme` proposal it shows the execute calls button even if the proposal hasn't been passed yet.
See: https://alchemy.daostack.io/dao/0x519b70055af55a007110b4ff99b0ea33071c720a/scheme/0x252d4c96bc18c6e0670f5cebeda40d6997688223d9498c8a61e0cb45c2c0a3ff
> Fix execute call button condition

- src/components/Proposal/Create/SchemeForms/ABIService.ts
fix #2413 
for now there is no simple way to get a proxy contract implementation address as it hidden (private) in most cases.
as a workaround alchemy will maintain a map of proxy-contracts to their implementation in order to fetch the proper Abis from etherscan.
this later on can be approved by indexing and fetching the Abis for the Multicall from the subgraph/ipfs,
> mcgs - hard coded proxy contracts support - workaround.
