package-lock.json, package.json
addresses  #4 and a couple other problems I encountered after fixing that one.
Note:  One of the other problems was that the `start` script was failing to bring up an instance of a browser, which was also leading to a bunch of subsequent errors.  Since the readme makes no mention of a browser firing up by itself, instead giving us the URL to browse to on our own, I simply removed the "--open" part that was causing the problems.
=> fixed issues with auto-start-ganache

package.json, src/reducers/arcReducer.ts
since it has been causing problems for me and @leviadam.
=> fix #10: remove `immutability-helper`

package.json, src/reducers/arcReducer.ts
This reverts #11 and fixes `immutability-helper`'s version to `2.6.4`.
Confirmed working for me.
@leviadam You may also want to confirm if it's working for you.
=> Revert immutability helper

src/actions/arcActions.ts, src/components/Proposal/Proposal.scss, src/components/Proposal/Proposal.scss.d.ts, src/components/Proposal/ProposalContainer.tsx, src/components/Proposal/ViewProposalContainer.tsx, src/components/Proposal/VoteBox.tsx, src/reducers/arcReducer.ts
- Show whether current user already voted on each proposal and what their vote was
- In proposal history list show the total DAO reputation at the time the proposal was executed
=> Correctly show votes

package-lock.json, package.json, src/actions/arcActions.ts, src/components/CreateProposal/CreateProposal.scss, src/components/CreateProposal/CreateProposal.scss.d.ts, src/components/CreateProposal/CreateProposalContainer.tsx
resolve #18 
Question: is there a better place to put validation logic?
=> Create proposal validation

package.json, src/layouts/App.scss, src/layouts/App.scss.d.ts, src/layouts/HeaderContainer.tsx, typings/build.d.ts, webpack.base.config.js
Resolve #24 
Inject version from `package.json` and latest commit hash to app. 
Display them in `HeaderContainer`.
=> inject version and commit hash from webpack, display in app

src/actions/notificationsActions.ts, src/components/Notification/Notification.scss, src/components/Notification/Notification.scss.d.ts, src/components/Notification/Notification.tsx, src/layouts/App.scss, src/layouts/App.scss.d.ts, src/layouts/AppContainer.tsx, src/layouts/HeaderContainer.tsx, src/reducers/index.ts, src/reducers/notificationsReducer.ts
Remove alerts in the `HeaderContainer` in favor of stacked dismissable notifications at the bottom right.
**Note:** Although I did some styling, it still needs a proper styling.
=> Stacked notifications

src/actions/arcActions.ts
the dangers of regex search based refactorings...
=> fix `Util.fromWei(..).toNumber()` regex replace errors

src/components/Notification/Notification.scss
I was finding the current success notification colors hard to read.
=> change success notification colors for better contrast

src/assets/styles/_rc-tooltip.scss, src/components/Proposal/Proposal.scss, src/components/Proposal/Proposal.scss.d.ts, src/components/Proposal/ProposalContainer.tsx, src/components/Proposal/ViewProposalContainer.tsx, src/components/ViewDao/DaoMembersContainer.tsx, src/layouts/HeaderContainer.tsx
Question: `ViewProposalContainer` contains duplicate code with `ProposalContainer`. Shouldn't we just use `ProposalContainer` from `ViewProposalContainer`?
=> show relative rep with tooltip

src/actions/arcActions.ts, src/components/Proposal/PredictionBox.tsx, src/reducers/arcReducer.ts
=> show GEN until boosted

src/components/Account/Account.scss, src/components/Account/AccountPopupContainer.tsx, src/components/Account/ReputationView.tsx, src/components/Proposal/Proposal.scss, src/components/Proposal/ProposalContainer.tsx, src/components/Proposal/VoteBox.tsx, src/layouts/HeaderContainer.tsx
- Refactored displaying reputation into a component `ReputationView`.
- Added two more places.
=> show rep tooltip everywhere

src/components/Proposal/ProposalContainer.tsx, src/components/ViewDao/DaoHistoryContainer.tsx, src/components/ViewDao/DaoProposalsContainer.tsx, src/selectors/daoSelectors.ts
Question: Should there be a separate section in history for expired proposals vs successfully executed?
=> move expired proposals to history

src/components/Proposal/Proposal.scss, src/components/ViewDao/ViewDao.scss, src/reducers/arcReducer.ts
Fix redemptions disappearing when they fail. 
Fix tooltip disappearing when you try to redeem
Add pointer cursor to the redeem buttons
=> Redeem fixes

src/actions/arcActions.ts, src/components/Proposal/ProposalContainer.tsx
Show correct beneficiary redemption rewards for expired boosted passed proposals
Also show in history whether a proposal passed or failed by decision or timeout
https://trello.com/c/cdsakMOO
=> Boosted beneficiary rewards

src/actions/arcActions.ts, src/actions/web3Actions.ts
To make sure they always match each other
https://trello.com/c/4E9ypJRH
=> Lowercase all account addresses used throughout the app

package-lock.json, package.json, src/components/CreateProposal/CreateProposalContainer.tsx
using [Formik](https://github.com/jaredpalmer/formik).
=> Validate create proposal form

package-lock.json, package.json, src/actions/arcActions.ts
Make sure any confirmed proposals have their server data updated with the correct proposalId
=> Make sure any confirmed proposals have their server data updated with the correct proposalId

src/components/CreateProposal/CreateProposalContainer.tsx
Fixed loading image issue -- filename case sensitivity :)
=> Frontend fixes

src/components/Proposal/PredictionBox.tsx
Disable button and show appropriate tooltip.
=> disable staking more than balance or zero

src/actions/arcActions.ts, src/components/CreateProposal/CreateProposalContainer.tsx, src/components/Proposal/ProposalContainer.tsx, src/reducers/arcReducer.ts
If they have more yes votes than no
=> Fix bug that shows expired non-boosted proposals as passed

package-lock.json, package.json, src/actions/arcActions.ts, src/components/Notification/Notification.tsx, src/layouts/AppContainer.tsx, src/reducers/index.ts, src/reducers/notifications.ts, src/reducers/operations.ts, typings/react-likify.d.ts
=> persistent transactions fixes

app.json, package.json, src/actions/web3Actions.ts, src/bg_cache_worker.ts, webpack.dev.config.js, webpack.prod.config.js
For [Review apps](https://devcenter.heroku.com/articles/github-integration-review-apps) to work we need to commit this `app.json` file that specifies the configuration of the review app.
=> Review apps

src/actions/arcActions.ts, src/components/ViewDao/ViewDaoContainer.tsx, src/selectors/daoSelectors.ts
Also only check open proposals for expiration
https://trello.com/c/YuyuXlba
=> Show a notification when a proposal times out/expires

src/reducers/notifications.ts
The bug appeared when rehydrating notifications when `state.web3.networkId` is still undefined
=> get network id from arc.js instead of state.web3

package.json, src/actions/arcActions.ts, src/bg_cache_worker.ts, src/components/ViewDao/ViewDaoContainer.tsx, src/index.tsx, src/layouts/AppContainer.tsx
- Update to arc.js alpha.72
- Use default depth on event watchers.
=> Sync notifcations with ui

package.json, src/actions/arcActions.ts, src/bg_cache_worker.ts, src/components/ViewDao/ViewDaoContainer.tsx, src/index.tsx, src/layouts/AppContainer.tsx, src/reducers/notifications.ts
This PR is only for testing the `dev` branch (via Review Apps) until the changes are merged into `staging`. As requested by Dor.
=> TEST PR - DO NOT MERGE

src/actions/arcActions.ts, src/components/Proposal/PredictionBox.tsx, src/reducers/arcReducer.ts
It comes from the DAO now, not per proposal
=> Make sure threshold to boost is always up to date and correct

src/components/Proposal/ProposalContainer.tsx
Whoa look, and we can clean up duplicate code in ProposalContainer!
https://trello.com/c/6YDMezEq
=> Show proposal creators/proposers in the history

src/components/Proposal/ProposalContainer.tsx, src/components/Shared/PreTransactionModal.tsx, src/components/ViewDao/DaoRedemptionsContainer.tsx
Make sure we have & separators but not an extra one at the beginning of the rewards string
Add rounding in a couple more places
=> Fix display of rewards throughout the app

src/actions/arcActions.ts, src/components/Proposal/Proposal.scss, src/components/Proposal/Proposal.scss.d.ts, src/components/Proposal/ProposalContainer.tsx, src/reducers/arcReducer.ts
=> Don’t show execute button for already executed proposals

src/components/Proposal/ProposalContainer.tsx
0xb0c908140fe6fd6fbd4990a5c2e35ca6dc12bfb2
=> Always show unredeemable beneficiary rewards in Redeem tooltip

src/components/Home/HomeContainer.tsx
Updated "Get Involved" link (was driving to dead Telegram channel) to drive to Discord community
=> Update Get Involved link to drive to Discord

src/components/Shared/PreTransactionModal.tsx
Fixing text on Alchemy screen.
=> Fixing text

README.md
Also clean up some
https://github.com/daostack/alchemy/issues/236
=> Update README with more Ganache private keys for MetaMask

.travis.yml, README.md, docker-compose.yml, package-lock.json, package.json, src/arc.ts, src/components/CreateProposal/CreateProposalContainer.tsx, src/components/Proposal/ProposalContainer.tsx, src/components/Proposal/RewardsString.tsx, src/components/Proposal/ViewProposalContainer.tsx, webpack.base.config.js
=> 265 upgrade client dependency (to 18), fix memory error in travis

src/lib/util.ts
https://github.com/daostack/alchemy/issues/280
=> Fix use of BigNumbers throughout the app

README.md, package-lock.json, package.json, src/components/Account/AccountBalances.tsx, src/components/Account/AccountPopupContainer.tsx, src/components/Account/AccountProfileContainer.tsx, src/components/CreateProposal/CreateProposalContainer.tsx, src/components/DaoList/DaoContainer.tsx, src/components/Proposal/ProposalContainer.tsx, src/components/Proposal/RedemptionsTip.tsx, src/components/Proposal/ViewProposalContainer.tsx, src/components/Shared/UserSearchField.tsx, src/components/ViewDao/DaoHistoryContainer.tsx, src/components/ViewDao/DaoMembersContainer.tsx, src/components/ViewDao/DaoProposalsContainer.tsx, src/components/ViewDao/DaoRedemptionsContainer.tsx, src/components/ViewDao/DaoSidebar.tsx, src/components/ViewDao/ViewDaoContainer.tsx, src/layouts/HeaderContainer.tsx, test/integration/members.ts
=> upgrade client to 0.0.26

README.md, package-lock.json, package.json, test/integration/members.ts
=> fix tests on dev

docs/development.md, src/components/Proposal/ClosedProposalContainer.tsx, src/components/Proposal/RedemptionsTip.tsx, src/components/ViewDao/DaoHistoryContainer.tsx, src/components/ViewDao/DaoProposalsContainer.tsx
Move proposals expired in the Queue instantly to the history page
https://github.com/daostack/alchemy/issues/305
=> Expired proposals

src/components/Account/AccountBalance.tsx, src/components/Account/AccountBalances.tsx, src/components/Proposal/ClosedProposalContainer.tsx, src/components/Proposal/ProposalContainer.tsx, src/components/Proposal/RedeemButton.tsx, src/components/Proposal/RedemptionsTip.tsx, src/components/Proposal/VoteBox.tsx, src/components/Shared/Subscribe.tsx, src/components/ViewDao/DaoProposalsContainer.tsx, src/components/ViewDao/ViewDaoContainer.tsx, src/layouts/AppContainer.tsx, src/layouts/HeaderContainer.tsx
=> improve current account handling and some refactoring

docker-compose.yml, package-lock.json, package.json
=>  upgrade client lib to 0.0.35

src/components/Proposal/PredictionBox.tsx, src/components/Proposal/ProposalContainer.tsx
And don’t show button if already approved
Fixes https://github.com/daostack/alchemy/issues/359 and https://github.com/daostack/alchemy/issues/380
=> Fix approval of GEN staking allowance

src/components/Proposal/PredictionBox.tsx, src/components/Proposal/ProposalContainer.tsx, src/components/Proposal/VoteBox.tsx
https://github.com/daostack/alchemy/issues/404
=> Allow for staking when in PreBoosted state

src/components/ViewDao/ViewDaoContainer.tsx
https://github.com/daostack/alchemy/issues/399
=> Disable tour for now

README.md, docs/docker.md
=> update readme files

src/actions/arcActions.ts, src/components/CreateProposal/CreateProposalContainer.tsx, src/components/Proposal/Proposal.scss, src/components/Proposal/Proposal.scss.d.ts, src/components/Proposal/ProposalContainer.tsx
Can add URL when creating a proposal
Description and Url displayed in proposal detail page
Still needs more styling from @brodeur 
Fixes https://github.com/daostack/alchemy/issues/408
=> Support proposal descriptions and URLs

package-lock.json, package.json, src/actions/arcActions.ts, src/components/CreateProposal/CreateProposalContainer.tsx, src/components/Proposal/VoteBox.tsx, src/reducers/arcReducer.ts
This fixes the proposal.winningOutcome type, references here: https://github.com/daostack/client/issues/141
=> use daostack/client version 0.0.37

docker-compose.yml, package-lock.json, package.json, src/arc.ts, src/components/CreateProposal/CreateProposalContainer.tsx, src/components/Proposal/ClosedProposalContainer.tsx, src/components/Proposal/ProposalContainer.tsx, src/components/Proposal/VoteBox.tsx, src/components/Shared/PreTransactionModal.tsx, src/components/ViewDao/DaoHistoryContainer.tsx, src/components/ViewDao/DaoRedemptionsContainer.tsx
- upgrade clietn to fix bug in ethBalance subscription
- upgrade client and docker containers to version 0.0.40
- refactor redemptions container with new query
=> [WIP] various

package-lock.json, package.json, src/actions/arcActions.ts, src/actions/profilesActions.ts, src/actions/web3Actions.ts, src/components/Account/AccountPopupContainer.tsx, src/components/Account/AccountProfileContainer.tsx, src/components/CreateProposal/CreateProposalContainer.tsx, src/components/Home/HomeContainer.tsx, src/components/Proposal/PredictionBox.tsx, src/components/Proposal/ProposalContainer.tsx, src/components/Proposal/VoteBox.tsx, src/components/Shared/PreTransactionModal.tsx, src/components/ViewDao/DaoMembersContainer.tsx, src/components/ViewDao/DaoProposalsContainer.tsx, src/components/ViewDao/DaoRedemptionsContainer.tsx, src/lib/util.ts, src/reducers/arcReducer.ts, src/selectors/daoSelectors.ts, tslint.json
- fix bug in calculating total rewards
- update client to 0.0.41, which as more aggrssive fetch policy - this fixes #400 
- use notifications for connection status instead of alerts - this fixes #438 
- restore linter triple-equals rule
- show notifications on proposal execute action [a first step towards implemeting #317
=> Cache management and other fixes

package-lock.json, package.json
- update client, which fixes #462
=> [WIP] various fixes

src/components/Proposal/ProposalContainer.tsx
https://github.com/daostack/alchemy/issues/464
=> Fix display of Redeem button

src/components/Proposal/Proposal.scss, src/components/Proposal/RedemptionsString.tsx, src/components/Proposal/VoteBox.tsx
https://github.com/daostack/alchemy/issues/498
=> Fix vote buttons on details page

src/components/Shared/PreTransactionModal.scss, src/components/Shared/PreTransactionModal.tsx
Make sure you can click on the input for # GENs
Don’t hide the cancel button when there are too many GENs entered.
=> Fix some bugs in the pre transaction modal for staking

src/components/Proposal/ProposalContainer.tsx
Fixes https://github.com/daostack/alchemy/issues/473
=> When a Queued proposal expires, hide it from the queue

src/arc.ts
Also reload the page when the user locks MetaMask
=> Fix bug when there is no ETH account

src/arc.ts
[this is already deployed to staging]
=> ipfs urls for staging and production

src/components/Account/AccountBalance.tsx, src/components/Account/AccountBalances.tsx, src/components/Account/AccountProfileContainer.tsx, src/components/Account/ReputationView.tsx, src/components/DaoList/DaoContainer.tsx, src/components/Proposal/ClosedProposalContainer.tsx, src/components/Proposal/PredictionBox.tsx, src/components/Proposal/Proposal.scss, src/components/Proposal/RedemptionsString.tsx, src/components/Proposal/RedemptionsTip.tsx, src/components/Proposal/RewardsString.tsx, src/components/Proposal/VoteBox.tsx, src/components/ViewDao/DaoRedemptionsContainer.tsx, src/components/ViewDao/DaoSidebar.tsx, src/lib/util.ts
Fixes https://github.com/daostack/alchemy/issues/510
=> Create function for consistently formatting tokens throughout the app

src/layouts/AppContainer.tsx, test/integration/history.ts, test/integration/members.ts, test/integration/profile.ts, test/integration/proposal.ts, test/integration/rewards.ts
Also fix stale element warning in proposal test
=> Remove disclaimer code, speed up tests

src/arc.ts, src/components/CreateProposal/CreateProposalContainer.tsx, src/components/Proposal/PredictionBox.tsx, src/components/Proposal/ProposalContainer.tsx, src/components/Proposal/VoteBox.tsx, src/components/Shared/PreTransactionModal.tsx, src/layouts/AppContainer.tsx, src/lib/util.ts
This is kind of a hack for now because the only function i could get working consistently is web3.eth.net.getNetworkType which returns a string and doesnt know if we are connected to ganache. When we upgrade web3 we should be able to use web3.eth.getChainId
=> Fix network warning

package-lock.json, package.json
should fix the eth balance of  #576
=> bump client to 52

webpack.base.config.js
=> support Kyber(KNC) as external token rewards.

src/components/Proposal/ActionButton.scss, src/components/Proposal/ActionButton.tsx, src/components/Proposal/Predictions/BoostAmount.tsx, src/components/Proposal/Predictions/PredictionButtons.scss
- If a proposal moves below the threshold to stay pre-boosted show amount needed to stake pass to keep it above threshold
- A couple positioning and style fixes to redeem button and proposal card
=> Little fixes to proposal cards

src/components/ViewDao/DaoRedemptionsContainer.tsx
Fixes https://github.com/daostack/alchemy/issues/681
=> Fix crashing rewards page

package-lock.json, package.json
=> Revert "client version 0.1.14"

package-lock.json, webpack.prod.config.js
Address #529.
Decrease bundle size from 14.88mb to 6.52mb parsed, and to 1.45mb zipped
=> Bundle size

package.json, src/components/Account/AccountProfileContainer.tsx, src/components/ViewDao/DaoSidebar.tsx, src/components/ViewDao/ViewDao.scss, src/components/ViewDao/ViewDao.scss.d.ts, src/components/ViewDao/ViewDaoContainer.tsx
Redemptions menu item should display feedback when user has unclaimed redemptions
=> Redemptions menu item should display feedback when user has unclaimed redemptions

package-lock.json, package.json
=> use client version 0.1.23 and fix the max-event-listeners warning

package-lock.json, package.json, src/App.tsx
- using the id `UA-142546205-2` (need to change to `UA-142546205-1` for production)
=> Google analytics test

src/components/ViewDao/DaoSidebar.tsx, src/components/ViewDao/ViewDao.scss
https://daostack.tpondemand.com/RestUI/Board.aspx#page=board/5209716961861964288&appConfig=eyJhY2lkIjoiQjgzMTMzNDczNzlCMUI5QUE0RUE1NUVEOUQyQzdFNkIifQ==&boardPopup=userstory/775/silent
=> Cleaned up sidebar dao icon and minimum height to support 3 tokens

src/components/DaoList/DaoContainer.tsx, src/components/DaoList/DaoList.scss, src/components/DaoList/DaoListContainer.tsx, src/components/ViewDao/DaoRedemptionsContainer.tsx, src/components/ViewDao/SchemeProposalsContainer.tsx
- remove TODO from dao card
- order daos by reputaitonholderscount
- order proposals by their expiry time
- order redemptions by age (when they were settled)
=> Low hanging fruit

src/actions/arcActions.ts, src/actions/web3Actions.ts, src/components/Account/AccountPopupContainer.tsx, src/components/Account/AccountProfileContainer.tsx, src/components/Account/ReputationView.tsx, src/components/CreateProposal/SchemeForms/CreateContributionRewardProposal.tsx, src/components/Notification/Notification.tsx, src/components/Proposal/Predictions/PredictionGraph.tsx, src/components/Proposal/ProposalSummary/ProposalSummarySchemeRegistrar.tsx, src/components/Proposal/RedemptionsTip.tsx, src/components/Proposal/Voting/VoteGraph.tsx, src/components/Shared/PreTransactionModal.tsx, src/components/ViewDao/DaoMembersContainer.tsx, src/layouts/HeaderContainer.tsx, src/lib/util.ts, src/reducers/notifications.ts
Also do a nice refactor by removing the Util class and making all the util functions individual exports
=> Fix bug with decimal external token rewards being turned into integers

package-lock.json, package.json, src/components/Proposal/ProposalCardContainer.tsx, src/components/Proposal/ProposalDetailsContainer.tsx, src/components/Proposal/Voting/VoteBreakdown.tsx, src/components/Proposal/Voting/VoteGraph.tsx, src/components/Proposal/Voting/VotersModal.tsx, src/components/Shared/PreTransactionModal.tsx, src/components/ViewDao/SchemeCardContainer.tsx
Instead of current DAO total rep
=> Display vote percentages using proposal.totalRepWhenCreated

src/components/Proposal/ProposalDetails.scss
https://daostack.tpondemand.com/RestUI/Board.aspx#page=board/5209716961861964288&appConfig=eyJhY2lkIjoiQjgzMTMzNDczNzlCMUI5QUE0RUE1NUVEOUQyQzdFNkIifQ==&boardPopup=bug/1011/silent
=> Fixed proposal details relative widths

package.json, src/arc.ts, src/components/Account/AccountProfileContainer.tsx, src/components/CreateProposal/SchemeForms/CreateContributionRewardProposal.tsx, src/components/CreateProposal/SchemeForms/CreateKnownGenericSchemeProposal.tsx, src/components/CreateProposal/SchemeForms/CreateSchemeRegistrarProposal.tsx, src/components/CreateProposal/SchemeForms/CreateUnknownGenericSchemeProposal.tsx, src/components/Proposal/ActionButton.tsx, src/components/Proposal/Predictions/PredictionButtons.tsx, src/components/Proposal/Voting/VoteBreakdown.tsx, src/components/Proposal/Voting/VoteButtons.tsx, src/components/Shared/PreTransactionModal.tsx, src/layouts/AppContainer.tsx, src/layouts/HeaderContainer.tsx, src/lib/util.ts
Add support for Gnosis Safe extension
=> Add support for Gnosis Safe extension

src/components/CreateProposal/SchemeForms/CreateKnownGenericSchemeProposal.tsx, src/components/Proposal/ProposalSummary/ProposalSummaryDutchX.tsx, src/genericSchemeRegistry/index.ts, src/genericSchemeRegistry/schemes/DutchX.json, src/lib/util.ts
- fix form address validation (tp  issue 1256)
- remove alerts
=> dutchx form validation - check for valid address

src/components/ViewDao/DaoHistoryContainer.tsx, src/components/ViewDao/DaoMembersContainer.tsx, src/components/ViewDao/SchemeProposalsContainer.tsx, src/components/ViewDao/ViewDaoContainer.tsx
Fixes https://github.com/daostack/alchemy/issues/886, https://github.com/daostack/alchemy/issues/887 and 
https://daostack.tpondemand.com/RestUI/Board.aspx#page=board/5209716961861964288&appConfig=eyJhY2lkIjoiQjgzMTMzNDczNzlCMUI5QUE0RUE1NUVEOUQyQzdFNkIifQ==&boardPopup=bug/1264/silent
=> 1264 fix infinite scrolling

src/assets/images/Icon/v-white-thick.svg, src/layouts/App.scss, src/layouts/App.scss.d.ts, src/layouts/AppContainer.tsx
Resolves: https://daostack.tpondemand.com/RestUI/Board.aspx#page=board/5209716961861964288&appConfig=eyJhY2lkIjoiQjgzMTMzNDczNzlCMUI5QUE0RUE1NUVEOUQyQzdFNkIifQ==&boardPopup=feature/1280/silent
**Note** the text is currently just a placeholder.
=> Cookie prompt

package-lock.json, package.json, src/components/CreateProposal/CreateProposalContainer.tsx, src/components/CreateProposal/SchemeForms/CreateKnownGenericSchemeProposal.tsx, src/components/CreateProposal/SchemeForms/CreateSchemeRegistrarProposal.tsx, src/components/Proposal/ProposalSummary/ProposalSummary.tsx, src/components/ViewDao/SchemeCardContainer.tsx, src/components/ViewDao/SchemeProposalsContainer.tsx, src/genericSchemeRegistry/schemes/DutchX.json, src/lib/util.ts, test/integration/utils.ts
=> 911 dutchx sniffing

package-lock.json, src/components/Proposal/ProposalDetails.scss, src/layouts/App.scss
Made a max image with to address half of the issue in
https://github.com/daostack/alchemy/issues/890
So now images will never be larger than the flex container
=> Max image width for proposal descriptions

package-lock.json, src/layouts/App.scss
This removes the scrollbars on proposal create modal for users who have "Always show scrollbars" enabled.
=> Removed scroll property

.eslintrc, src/components/Account/AccountProfileContainer.tsx, src/components/CreateProposal/SchemeForms/CreateContributionRewardProposal.tsx, src/components/CreateProposal/SchemeForms/CreateKnownGenericSchemeProposal.tsx, src/components/CreateProposal/SchemeForms/CreateSchemeRegistrarProposal.tsx, src/components/CreateProposal/SchemeForms/CreateUnknownGenericSchemeProposal.tsx, src/components/Proposal/Predictions/BoostAmount.tsx, src/components/Proposal/Predictions/PredictionButtons.tsx, src/components/Proposal/ProposalDetailsContainer.tsx, src/components/Shared/PreTransactionModal.tsx, src/components/ViewDao/ViewDaoContainer.tsx, src/layouts/HeaderContainer.tsx
Fixes unnecessary escape errors
0 errors, 766 warnings
=> fix escape errors

.eslintrc
remaining: 0 errors, 522 warnings
=> remove max-len lint rule

test/integration/proposal.ts
=> make proposal test more robust

src/components/ViewDao/ViewDao.scss
https://daostack.tpondemand.com/RestUI/Board.aspx#page=board/5209716961861964288&appConfig=eyJhY2lkIjoiQjgzMTMzNDczNzlCMUI5QUE0RUE1NUVEOUQyQzdFNkIifQ==&boardPopup=userstory/1324/silent
=> Styled reputation holders

src/components/ViewDao/ViewDao.scss
https://daostack.tpondemand.com/RestUI/Board.aspx#page=board/5209716961861964288&appConfig=eyJhY2lkIjoiQjgzMTMzNDczNzlCMUI5QUE0RUE1NUVEOUQyQzdFNkIifQ==&boardPopup=bug/1326/silent
=> Fixed styling of mobile alpha notice

src/actions/async.ts, src/components/Proposal/ProposalCardContainer.tsx, src/components/Proposal/ProposalDetailsContainer.tsx, src/components/Proposal/ProposalHistoryRow.tsx, src/lib/util.ts, src/reducers/arcReducer.ts, src/reducers/profilesReducer.ts, src/reducers/uiReducer.ts, src/reducers/web3Reducer.ts, src/schemas/index.ts
a few small things revealed by txPrune.  Some of them involve simply removing unneeded `export` .
webpack tree-shaking is giving no additional satisfaction
=> tsPrune results

src/components/Daos/Daos.scss
https://daostack.tpondemand.com/RestUI/Board.aspx#page=board/5209716961861964288&appConfig=eyJhY2lkIjoiQjgzMTMzNDczNzlCMUI5QUE0RUE1NUVEOUQyQzdFNkIifQ==&boardPopup=feature/1327/silent
=> Made DAO cards smaller and added nice corners

src/components/Proposal/Voting/VoteButtons.tsx
note that this PR is against master since this is an urgent broken thing on production right now
=> Fix voted for/against icons

package-lock.json, package.json
- upgrade cleint to 0.2.3
- fix "member not ofund" bug
=> fix "member not found" bug

src/components/Dao/Dao.scss
Fixed font styling in the sidebar
=> Sidebar polish

src/arc.ts, src/layouts/Header.tsx
Resolves: #1006 
Resolves: #1007
=> no app restart, block only on tx send

src/arc.ts, src/layouts/AppContainer.tsx
Resolves: #1013 
**Note** Logging out via MM will now have the same behavior as logging out from within the app. 
See:  https://github.com/daostack/alchemy/issues/1011
=> don't freeze login button after MM account logout

src/components/Proposal/ActionButton.scss
https://daostack.tpondemand.com/RestUI/Board.aspx#page=board/5209716961861964288&appConfig=eyJhY2lkIjoiQjgzMTMzNDczNzlCMUI5QUE0RUE1NUVEOUQyQzdFNkIifQ==&boardPopup=bug/1396/silent
=> Fixed hover issue which resulted in flickering width of boost button

package-lock.json, src/components/Dao/Dao.scss, src/components/Proposal/Create/CreateProposal.scss, src/components/Proposal/Create/SchemeForms/CreateUnknownGenericSchemeProposal.tsx, src/components/Scheme/Scheme.scss, src/components/Scheme/SchemeInfo.scss, src/components/Scheme/SchemeInfoPage.tsx, src/layouts/App.scss
https://daostack.tpondemand.com/RestUI/Board.aspx#page=board/5209716961861964288&appConfig=eyJhY2lkIjoiQjgzMTMzNDczNzlCMUI5QUE0RUE1NUVEOUQyQzdFNkIifQ==&boardPopup=bug/1394/silent
=> 1393, 1394, 1400:  scheme info tab, queue header, mobile forms 

src/components/Dao/DaoMembersPage.tsx, src/components/Shared/Subscribe.tsx
https://github.com/daostack/alchemy/issues/1020
=> Fix incorrect use of setState in render() function of Subscribe

.travis.yml, package-lock.json, package.json, src/App.spec.tsx, src/arc.ts, src/components/Shared/Countdown.spec.tsx, src/lib/util.ts, test/integration/rewards.ts, test/unit/util.spec.ts
* define `npm run test:unit`
* write a unit test for formatToken
* make sure that formatToken rounds down (to address https://daostack.tpondemand.com/RestUI/Board.aspx#page=profile&boardPopup=userstory/1258/silent)
* make the App.spec js test work
=> add basic unit test

src/components/Dao/DaoSchemesPage.tsx
Resolves: https://daostack.tpondemand.com/RestUI/Board.aspx#page=board/5209716961861964288&appConfig=eyJhY2lkIjoiQjgzMTMzNDczNzlCMUI5QUE0RUE1NUVEOUQyQzdFNkIifQ==&boardPopup=userstory/1432/silent
**Note** I also added sorting the schemes by name, asc.
=> Put Contribution Reward first in list of schemes

CHANGELOG.md, src/actions/arcActions.ts, src/components/Scheme/ReputationFromToken.tsx, src/components/Scheme/Scheme.scss, src/components/Scheme/SchemeContainer.tsx
This PR implements the functionality from issue https://github.com/daostack/alchemy/issues/1036
=> redeem with private key

src/lib/util.ts, test/unit/util.spec.ts
Resolves: https://daostack.tpondemand.com/RestUI/Board.aspx#page=board/5209716961861964288&appConfig=eyJhY2lkIjoiQjgzMTMzNDczNzlCMUI5QUE0RUE1NUVEOUQyQzdFNkIifQ==&boardPopup=bug/1118/silent
- Displays large numbers as billions.
- cleans up utils.formatTokens
=> handle super big numbers, displaying as billions

src/components/Proposal/Voting/VoteGraph.tsx
Resolves: https://daostack.tpondemand.com/RestUI/Board.aspx#page=board/5209716961861964288&appConfig=eyJhY2lkIjoiQjgzMTMzNDczNzlCMUI5QUE0RUE1NUVEOUQyQzdFNkIifQ==&boardPopup=bug/1451/silent
=> show proposal is failing when vote is tied

src/components/Scheme/SchemeInfo.scss, src/components/Scheme/SchemeInfoPage.tsx
Resolves: https://daostack.tpondemand.com/RestUI/Board.aspx#page=board/5209716961861964288&appConfig=eyJhY2lkIjoiQjgzMTMzNDczNzlCMUI5QUE0RUE1NUVEOUQyQzdFNkIifQ==&boardPopup=bug/1427/silent
=> Scheme Info Page improvements

src/components/Proposal/ActionButton.tsx
Resolves: https://daostack.tpondemand.com/RestUI/Board.aspx#page=board/5209716961861964288&appConfig=eyJhY2lkIjoiQjgzMTMzNDczNzlCMUI5QUE0RUE1NUVEOUQyQzdFNkIifQ==&boardPopup=bug/1455/silent
=> don't calculate redeemables when there is no current account

src/components/Proposal/Create/SchemeForms/CreateContributionRewardProposal.tsx, src/components/Proposal/Create/SchemeForms/CreateKnownGenericSchemeProposal.tsx, src/components/Proposal/Create/SchemeForms/CreateSchemeRegistrarProposal.tsx, src/components/Proposal/Create/SchemeForms/CreateUnknownGenericSchemeProposal.tsx, src/lib/util.ts, test/unit/util.spec.ts
Resolves: https://daostack.tpondemand.com/RestUI/Board.aspx#page=board/5209716961861964288&appConfig=eyJhY2lkIjoiQjgzMTMzNDczNzlCMUI5QUE0RUE1NUVEOUQyQzdFNkIifQ==&boardPopup=bug/1315/silent
=> Fix and consolidate url validation

CHANGELOG.md, src/lib/util.ts, test/unit/util.spec.ts
Resolves: https://daostack.tpondemand.com/RestUI/Board.aspx#page=board/5209716961861964288&appConfig=eyJhY2lkIjoiQjgzMTMzNDczNzlCMUI5QUE0RUE1NUVEOUQyQzdFNkIifQ==&boardPopup=bug/914/silent
=> fix toWei for small fractions

src/assets/styles/_rc-tooltip.scss, src/assets/styles/global.scss, src/components/Notification/Notification.scss, src/components/Notification/Notification.tsx
- fixes Notifications issues described in the original PR:
-- https://github.com/daostack/alchemy/pull/1048#issuecomment-523472286
-- https://github.com/daostack/alchemy/pull/1048#issuecomment-523474927
-- https://github.com/daostack/alchemy/pull/1048#issuecomment-523477869
- cleans up Notifications code a little
=> clean up notifications code and layout

src/actions/arcActions.ts, src/components/Proposal/ActionButton.scss
- reveal Execute button text
- fix spelling of "Successful" message
Resolves: https://github.com/daostack/alchemy/issues/1068
Resolves: https://github.com/daostack/alchemy/issues/1035
=> reveal Execute button text

src/layouts/App.scss, src/layouts/Header.tsx
Resolves: #1080
Now looks like this:
=> fix Connect button layout on mobile

CHANGELOG.md, src/arc.ts, src/components/Dao/DaoRedemptionsPage.tsx, src/components/Proposal/ActionButton.tsx
- use subgraph v26 in staging
- add environment variables for subgraph connection
- remove obsolete hacky code
=> Use subgraph v26

src/actions/arcActions.ts, src/components/Dao/DaoSidebar.tsx
Resolves:  https://daostack.tpondemand.com/restui/board.aspx?#page=board/5209716961861964288&appConfig=eyJhY2lkIjoiQjgzMTMzNDczNzlCMUI5QUE0RUE1NUVEOUQyQzdFNkIifQ==&boardPopup=bug/1561/silent
Fixes lint error from another PR
=> ensure scheme.ReputationFromToken is set

src/components/Daos/DaoCard.tsx
Resolves: https://daostack.tpondemand.com/restui/board.aspx?#page=board/5209716961861964288&appConfig=eyJhY2lkIjoiQjgzMTMzNDczNzlCMUI5QUE0RUE1NUVEOUQyQzdFNkIifQ==&boardPopup=bug/1308/silent
=> show zero instead of ? when no members

src/components/Scheme/ReputationFromToken.tsx
=> fix rep4token error msg

src/components/Proposal/Create/CreateProposalPage.tsx
Resolves: https://daostack.tpondemand.com/restui/board.aspx?#page=board/5209716961861964288&appConfig=eyJhY2lkIjoiQjgzMTMzNDczNzlCMUI5QUE0RUE1NUVEOUQyQzdFNkIifQ==&boardPopup=bug/1518/silent
=> Show generic scheme name in new proposal title bar

src/components/Dao/Dao.scss, src/components/Dao/DaoSchemesPage.scss, src/components/Daos/Daos.scss, src/layouts/App.scss
https://daostack.tpondemand.com/RestUI/Board.aspx#page=board/5209716961861964288&appConfig=eyJhY2lkIjoiQjgzMTMzNDczNzlCMUI5QUE0RUE1NUVEOUQyQzdFNkIifQ==&boardPopup=userstory/1399/silent
=> Re-add mobile breadcrumbs

CHANGELOG.md, src/components/Dao/Dao.scss, src/components/Dao/DaoSidebar.tsx
Also fix Buy GEN menu so you can see the whole thing
https://daostack.tpondemand.com/RestUI/Board.aspx#page=board/5209716961861964288&appConfig=eyJhY2lkIjoiQjgzMTMzNDczNzlCMUI5QUE0RUE1NUVEOUQyQzdFNkIifQ==&boardPopup=userstory/1612/silent
=> Cleanup and update DAO menu with new help center

package-lock.json, package.json, src/components/Account/AccountPopup.tsx, src/components/Proposal/ProposalHistoryRow.tsx, src/components/Proposal/Voting/VoteBreakdown.tsx
- reduce number fo subscriptions for loading of [history page](http://127.0.0.1:3000/dao/0x294f999356ed03347c7a23bcbcf8d33fa41dc830/history/)  from 600 to 7
-
=> reduce number of subscriptions

CHANGELOG.md, src/components/Account/Account.scss, src/components/Account/AccountProfileName.tsx, src/components/Dao/Dao.scss, src/components/Dao/DaoHistoryPage.tsx, src/components/Proposal/ProposalHistoryRow.scss, src/components/Proposal/ProposalHistoryRow.tsx, src/components/Proposal/Staking/StakeGraph.scss, src/components/Proposal/Voting/VoteBreakdown.scss, src/components/Proposal/Voting/VoteBreakdown.tsx
This required shifting to a table and a lot of CSS changes.
@A-Zak make sure to test this good. Mobile in particular should be tested
=> Align headers of table in proposal history

CHANGELOG.md, src/App.tsx, src/layouts/App.scss, src/lib/util.ts
Resolves: https://github.com/daostack/alchemy/issues/1050
Resolves: https://daostack.tpondemand.com/RestUI/Board.aspx#page=board/5209716961861964288&appConfig=eyJhY2lkIjoiQjgzMTMzNDczNzlCMUI5QUE0RUE1NUVEOUQyQzdFNkIifQ==&boardPopup=bug/1597/silent
=> wait for good internet connection on startup

src/components/Proposal/RedemptionsTip.tsx
https://daostack.tpondemand.com/RestUI/Board.aspx#page=board/5209716961861964288&appConfig=eyJhY2lkIjoiQjgzMTMzNDczNzlCMUI5QUE0RUE1NUVEOUQyQzdFNkIifQ==&boardPopup=bug/1510/silent
=> Fix non-unique keys error on redeem button tooltip

CHANGELOG.md, src/components/Proposal/Create/SchemeForms/CreateSchemeRegistrarProposal.tsx, src/components/Proposal/ProposalSummary/ProposalSummarySchemeRegistrar.tsx, src/components/Scheme/SchemeInfoPage.tsx
Resolves: https://daostack.tpondemand.com/RestUI/Board.aspx#page=board/5209716961861964288&appConfig=eyJhY2lkIjoiQjgzMTMzNDczNzlCMUI5QUE0RUE1NUVEOUQyQzdFNkIifQ==&boardPopup=userstory/1599/silent
Resolves: https://github.com/daostack/alchemy/issues/1064
=> add static mint and burn permission

CHANGELOG.md, src/components/Daos/DaosPage.tsx
Resolves:  https://daostack.tpondemand.com/RestUI/Board.aspx#page=board/5209716961861964288&appConfig=eyJhY2lkIjoiQjgzMTMzNDczNzlCMUI5QUE0RUE1NUVEOUQyQzdFNkIifQ==&boardPopup=bug/1604/silent
Resolves: https://daostack.tpondemand.com/RestUI/Board.aspx#page=board/4789434231796866533&appConfig=eyJhY2lkIjoiMEFGRDcyNjIyOTgzRjFFMkMwRjIwMDBCNzA0QjRGMzQifQ==&boardPopup=bug/1644/silent
Resolves: https://github.com/daostack/alchemy/issues/1107
=> don't add Genesis Alpha on each render

package-lock.json, package.json, src/components/Proposal/ProposalSummary/ProposalSummaryDutchX.tsx
fixes bugs in current release candidate:
- show addresses of unknown schemes
- do not crash redemptiosn page is callDAta of proposal is not recognized
=> Release fixes

CHANGELOG.md, src/actions/uiActions.ts, src/components/Dao/Dao.scss, src/components/Dao/DaoSidebar.tsx, src/layouts/App.scss, src/layouts/Header.tsx, src/reducers/uiReducer.ts
Refactors the hamburger button to be part of the header instead of part of the sidebar.  This simplifies the coding and CSS layout out both of them.
Originally was about: https://daostack.tpondemand.com/RestUI/Board.aspx#page=board/5209716961861964288&appConfig=eyJhY2lkIjoiQjgzMTMzNDczNzlCMUI5QUE0RUE1NUVEOUQyQzdFNkIifQ==&boardPopup=bug/1623/silent
=> refactor hamburger button

src/components/Proposal/ProposalHistoryRow.tsx
Resolves: https://daostack.tpondemand.com/RestUI/Board.aspx#page=board/5209716961861964288&appConfig=eyJhY2lkIjoiQjgzMTMzNDczNzlCMUI5QUE0RUE1NUVEOUQyQzdFNkIifQ==&boardPopup=bug/919/silent
=> sum all stakes in history row

CHANGELOG.md, src/components/Proposal/ProposalDetailsPage.tsx, src/components/Proposal/Voting/VotersModal.tsx
Resolves: https://daostack.tpondemand.com/RestUI/Board.aspx#page=board/5209716961861964288&appConfig=eyJhY2lkIjoiQjgzMTMzNDczNzlCMUI5QUE0RUE1NUVEOUQyQzdFNkIifQ==&boardPopup=bug/1667/silent
=> show voters' name on VotersModal rows

CHANGELOG.md, src/components/Notification/Notification.scss, src/layouts/App.scss
Resolves: https://daostack.tpondemand.com/RestUI/Board.aspx#page=board/5209716961861964288&appConfig=eyJhY2lkIjoiQjgzMTMzNDczNzlCMUI5QUE0RUE1NUVEOUQyQzdFNkIifQ==&boardPopup=bug/1621/silent
=> notification color bar should be 100% width for every color

CHANGELOG.md, src/arc.ts, src/layouts/Header.tsx, test/integration/proposal-genericSchemeRegistryLookup.ts, test/integration/utils.ts
Resolves: https://daostack.tpondemand.com/RestUI/Board.aspx#page=board/5209716961861964288&appConfig=eyJhY2lkIjoiQjgzMTMzNDczNzlCMUI5QUE0RUE1NUVEOUQyQzdFNkIifQ==&boardPopup=bug/1717/silent
* Disallows any connection to a wrong network
* refactors to simplify code, particularly error handling and notification reporting
=> disallow txs against wrong networks

src/arc.ts
- fixes a bug in which the apolloclient cache is reset when connecting to eth provider
=> fix apolloclient cache reset

src/components/Proposal/Staking/StakeButtons.tsx, src/components/Shared/PreTransactionModal.tsx
Resolves: https://daostack.tpondemand.com/RestUI/Board.aspx#page=board/5209716961861964288&appConfig=eyJhY2lkIjoiQjgzMTMzNDczNzlCMUI5QUE0RUE1NUVEOUQyQzdFNkIifQ==&boardPopup=bug/1659/silent
=> remove staking warning tooltip

src/components/Proposal/Voting/VotersModal.tsx
Resolves: https://daostack.tpondemand.com/RestUI/Board.aspx#page=board/5209716961861964288&appConfig=eyJhY2lkIjoiQjgzMTMzNDczNzlCMUI5QUE0RUE1NUVEOUQyQzdFNkIifQ==&boardPopup=bug/1754/silent
Also removes subscription on voters
=> fix dup voter profiles in proposal voters dialog

package-lock.json, package.json
this new cliet newest v30 of the migraion repo, which contains (also) the latest versions of the contracts...
=> new client version

test/integration/wdio.conf.js
upgrade chromedriver version to latest so travis doesn't complain
=> fix chromedriver version

CHANGELOG.md, src/layouts/App.scss
Resolves: https://daostack.tpondemand.com/RestUI/Board.aspx#page=board/5209716961861964288&appConfig=eyJhY2lkIjoiQjgzMTMzNDczNzlCMUI5QUE0RUE1NUVEOUQyQzdFNkIifQ==&boardPopup=bug/1538/silent
=> improve cookie discalimer layout on mobile

CHANGELOG.md, src/components/Scheme/SchemeInfoPage.tsx, src/lib/util.ts
Resolves: https://daostack.tpondemand.com/RestUI/Board.aspx#page=board/5209716961861964288&appConfig=eyJhY2lkIjoiQjgzMTMzNDczNzlCMUI5QUE0RUE1NUVEOUQyQzdFNkIifQ==&boardPopup=bug/1534/silent
- rounds up at three digits
- provides tooltip of unrounded value
=> Round up scheme thresholdConst value

CHANGELOG.md, src/components/Shared/withSubscription.tsx
resolves: https://daostack.tpondemand.com/RestUI/Board.aspx#page=board/5209716961861964288&appConfig=eyJhY2lkIjoiQjgzMTMzNDczNzlCMUI5QUE0RUE1NUVEOUQyQzdFNkIifQ==&boardPopup=bug/1715/silent
=> fix hang on malformed DAO address (createObservable)

CHANGELOG.md, src/components/Proposal/Staking/StakeButtons.scss, src/components/Proposal/Staking/StakeButtons.tsx
Resolves: https://daostack.tpondemand.com/RestUI/Board.aspx#page=board/5209716961861964288&appConfig=eyJhY2lkIjoiQjgzMTMzNDczNzlCMUI5QUE0RUE1NUVEOUQyQzdFNkIifQ==&boardPopup=userstory/938/silent
=> add cancel button to staking preapprove prompt

src/components/Proposal/ProposalCard.tsx, src/components/Proposal/ProposalDetailsPage.tsx
fixes #1195 
Need to find the real cause - followup is in target process
=> hotfix for #1195

package-lock.json, package.json, src/components/Dao/DaoHistoryPage.tsx
=> Client 0.2.23

CHANGELOG.md, src/components/Scheme/SchemeInfoPage.tsx, src/lib/util.ts
Resolves: https://github.com/daostack/alchemy/issues/1173
Resolves: https://daostack.tpondemand.com/RestUI/Board.aspx#page=board/4789434231796866533&appConfig=eyJhY2lkIjoiMEFGRDcyNjIyOTgzRjFFMkMwRjIwMDBCNzA0QjRGMzQifQ==&boardPopup=bug/1751/silent
=> fix scheme activation time

CHANGELOG.md, src/assets/styles/_rc-tooltip.scss, src/components/Dao/DaoSidebar.tsx, src/components/Dao/ProposalSchemeCard.tsx, src/components/Proposal/Create/CreateProposal.scss, src/components/Proposal/Create/SchemeForms/CreateContributionRewardProposal.tsx, src/components/Proposal/Create/SchemeForms/CreateSchemeRegistrarProposal.tsx, src/components/Proposal/Create/SchemeForms/CreateUnknownGenericSchemeProposal.tsx, src/components/Proposal/ProposalCard.tsx, src/components/Scheme/SchemeContainer.tsx, src/components/Scheme/SchemeProposalsPage.tsx, src/components/Shared/TrainingTooltip.scss, src/components/Shared/TrainingTooltip.tsx, src/layouts/Header.tsx, src/lib/util.ts
Addresses: https://daostack.tpondemand.com/RestUI/Board.aspx#page=board/5209716961861964288&appConfig=eyJhY2lkIjoiQjgzMTMzNDczNzlCMUI5QUE0RUE1NUVEOUQyQzdFNkIifQ==&boardPopup=userstory/1797/silent
This simply adds tooltips that show up on mouse hover.
**Note** it is lacking the dynamically-computed boosted&preboosted times.
=> Add Training Tooltips - Phase I

src/components/Proposal/ProposalCard.tsx, src/components/Scheme/SchemeContainer.tsx, src/components/Scheme/SchemeProposals.scss, src/components/Scheme/SchemeProposalsPage.tsx, src/components/Shared/TrainingTooltip.scss, src/components/Shared/TrainingTooltip.tsx
- sets max width on tooltips
- shrinks hover area for proposal queue headers
- repositions one or two
=> tweaks to improve relative layout of tips

src/components/Proposal/ProposalCard.tsx, src/components/Scheme/SchemeProposalsPage.tsx
As a performance optimization, show training tooltips only on first proposal card of each proposal phase section
=> show tooltips only on first card of each section

src/components/Shared/TrainingTooltip.tsx, src/layouts/Header.tsx
Make the toggle button training tooltip always available, even when tooltips are disabled.
=> toggle tooltip always available

src/components/Dao/ProposalSchemeCard.tsx
Resolves: https://daostack.tpondemand.com/RestUI/Board.aspx#page=board/5209716961861964288&appConfig=eyJhY2lkIjoiQjgzMTMzNDczNzlCMUI5QUE0RUE1NUVEOUQyQzdFNkIifQ==&boardPopup=bug/1821/silent
=> eliminate empty tooltips

CHANGELOG.md, src/components/Proposal/ProposalDetailsPage.tsx
Resolves: https://daostack.tpondemand.com/RestUI/Board.aspx#page=board/5209716961861964288&appConfig=eyJhY2lkIjoiQjgzMTMzNDczNzlCMUI5QUE0RUE1NUVEOUQyQzdFNkIifQ==&boardPopup=bug/1785/silent
BTW, I think we could probably reduce a lot of rendering elsewhere in the app by using the same solution as used in this PR.
=> minimize rerendering of disqus component

src/App.tsx, src/components/Account/AccountProfilePage.tsx, src/components/Dao/DaoContainer.tsx, src/components/Proposal/ProposalSummary/ProposalSummarySchemeRegistrar.tsx, src/layouts/AppContainer.tsx
Related to:  https://daostack.tpondemand.com/RestUI/Board.aspx#page=board/5209716961861964288&appConfig=eyJhY2lkIjoiQjgzMTMzNDczNzlCMUI5QUE0RUE1NUVEOUQyQzdFNkIifQ==&boardPopup=bug/1798/silent
converts all UNSAFE_componentWillMount to componentDidMount
=> eliminate UNSAFE methods

src/components/Proposal/Voting/VotersModal.scss, src/components/Proposal/Voting/VotersModal.tsx
Resolves: https://daostack.tpondemand.com/RestUI/Board.aspx#page=board/5209716961861964288&appConfig=eyJhY2lkIjoiQjgzMTMzNDczNzlCMUI5QUE0RUE1NUVEOUQyQzdFNkIifQ==&boardPopup=bug/1811/silent
- eliminate vertical whitespace
- "Down" button => "Close"
- added textual feedback when there are no votes for one of either yes or no
- increased available horizontal display space (to make less likely to appear like below)
=> voter's details are too down at Votes popup

src/components/Proposal/ActionButton.tsx
Resolves: https://daostack.tpondemand.com/RestUI/Board.aspx#page=board/5209716961861964288&appConfig=eyJhY2lkIjoiQjgzMTMzNDczNzlCMUI5QUE0RUE1NUVEOUQyQzdFNkIifQ==&boardPopup=bug/1832/silent
=> ignore externalTokenReward when address is null

src/components/Proposal/Create/SchemeForms/CreateContributionRewardProposal.tsx
Resolves: https://daostack.tpondemand.com/RestUI/Board.aspx#page=board/5209716961861964288&appConfig=eyJhY2lkIjoiQjgzMTMzNDczNzlCMUI5QUE0RUE1NUVEOUQyQzdFNkIifQ==&boardPopup=bug/1822/silent
=> shorten token dropdown menu

src/components/Scheme/SchemeInfoPage.tsx
=> fix representation of duration in days

src/components/Proposal/RewardsString.tsx
Reproduce crash at this url:
https://alchemy.daostack.io/dao/0xdd3afee87b0b5b6ec89ee7287f7f0f0d5470f9db/proposal/0x92a472f2cb191a8c8b94c2580b70ce35c9525a0d8e4516830c68629eae7f310e
=> fixCrashInCorruptProposal

app.json
- set environment default values in heroku
=> fix heroku (which broke after upgrading the pipeline)

src/genericSchemeRegistry/schemes/RegistryLookup.json
=> 1304 ensregistry hotfix

src/layouts/SidebarMenu.tsx
https://daostack.tpondemand.com/RestUI/Board.aspx#page=board/5209716961861964288&appConfig=eyJhY2lkIjoiQjgzMTMzNDczNzlCMUI5QUE0RUE1NUVEOUQyQzdFNkIifQ==&boardPopup=bug/1861/silent
=> Remove duplicate privacy policy

src/actions/arcActions.ts, src/components/Proposal/RedemptionsString.tsx, src/components/Proposal/RedemptionsTip.tsx, src/components/Redemptions/RedemptionsPage.tsx, src/lib/util.ts
Also fix ability to execute proposals when DAO doesnt have funds to redeem for beneficiary.
=> Fix display of external token rewards (in particular USDC)

src/components/Feed/Feed.scss, src/components/Feed/FeedItem.tsx, src/components/Feed/FeedPage.tsx, src/components/Feed/ProposalFeedItem.tsx
Correctly wrap new lines in proposal descriptions
Dont show "Proposal" before every proposal title
Proposal feed item: Fix fade out to not cover Show more details link
Don't show expired proposal feed items when following a DAO
Correctly title expired proposal items
=> More feed fixes

src/components/Proposal/Create/SchemeForms/CreateSchemeRegistrarProposal.tsx
Fixes: https://github.com/daostack/alchemy/issues/1325
=> Default to Add Plugin form when creating Plugin Manager proposal

src/components/Shared/UserSearchField.tsx
When current user does not have a name
https://github.com/daostack/alchemy/issues/1315
=> Fix: Cannot read property 'includes' of undefined" in usersearchfield

src/components/Scheme/SchemeInfo.scss, src/components/Scheme/SchemeInfoPage.tsx
Make buttons have cursor pointer, and show a notification after copying
Fixes https://github.com/daostack/alchemy/issues/1228
=> Improve UX for copy address buttons on scheme info

src/components/Proposal/Staking/StakeButtons.tsx, src/components/Shared/PreTransactionModal.scss, src/components/Shared/PreTransactionModal.tsx
Get staking working
Make sure error doesnt overlap amount needed to boost text
Fixes: https://github.com/daostack/alchemy/issues/1350
=> Fix staking errors

src/components/Proposal/ProposalCard.tsx, src/components/Scheme/SchemeContainer.tsx
This means you cant click on the whole proposal card to go to the proposal details but you can click on all of the following:
- proposal title
- proposal description
- tags
- the timer
- the voting and staking section at the bottom of the card
=> Fix errors about nested <a> tags

data/tokens.json, src/components/Account/AccountBalances.tsx, src/components/Account/AccountProfilePage.tsx, src/components/Proposal/Create/SchemeForms/CreateContributionRewardProposal.tsx, src/components/Proposal/Create/SchemeForms/CreateUnknownGenericSchemeProposal.tsx, src/components/Proposal/RedemptionsString.tsx, src/components/Proposal/RedemptionsTip.tsx, src/components/Proposal/RewardsString.tsx, src/components/Redemptions/RedemptionsPage.tsx, src/components/Scheme/ContributionRewardExtRewarders/Competition/CreateProposal.tsx, src/layouts/SidebarMenu.tsx, src/lib/util.ts, src/settings.ts
Fixes parts of https://github.com/daostack/alchemy/issues/1363
Also gets rid of annoying token contracts missing errors on ganache and rinkeby, and uses correct token addresses on rinkeby
=> When on xdai network ETH becomes xDAI and GEN becomes xGEN

src/components/Proposal/Create/CreateProposal.scss, src/components/Proposal/Create/CreateProposalPage.tsx
If screen is too small then allow for scrolling the form content
Also add a close button to the header to make it easier to always get out, especially on mobile
Fixes https://github.com/daostack/alchemy/issues/1378
=> Make sure you can always see the whole create proposal form

src/components/Proposal/ProposalData.tsx
Fixes https://github.com/daostack/alchemy/issues/1374
Since i couldn't easily reproduce the warning this is a bit of guess, but I think it's the right guess :)
=> Fix warning about ProposalCard memory leak

src/components/Scheme/ContributionRewardExtRewarders/Competition/Details.tsx
Resolves: https://github.com/daostack/alchemy/issues/1404
=> fix green thumbs when no account

src/components/Proposal/ProposalDetailsPage.tsx
Resolves: https://github.com/daostack/alchemy/issues/1392
=> remove semicolon

src/components/Dao/ProposalSchemeCard.tsx, src/components/Dao/SchemeCard.scss
Resolves: https://github.com/daostack/alchemy/issues/1360
* refactors the code
* removes all the tab characters from Schemecard.scss
* enables long titles to wrap
=> fix layout of proposal summary card

src/index.tsx, src/lib/analytics.ts
=> Fix mixpanel tracking and add tracking of xdai alchemy

src/components/Scheme/ContributionRewardExtRewarders/Competition/CreateProposal.tsx, src/components/Scheme/ContributionRewardExtRewarders/Competition/Details.tsx, src/components/Scheme/ContributionRewardExtRewarders/Competition/List.tsx, src/components/Scheme/ContributionRewardExtRewarders/Competition/utils.ts
=> Revert "better caching for submission list"

src/arc.ts
which should never have been merged to dev :-/
=> Fix travis errors

src/settings.ts
Remove all test environment judging.
=> Update settings :)

src/components/Dao/Dao.scss, src/components/Dao/DaoContainer.tsx, src/index.html
Also hide support button mobile
TEMPORARY FOR ETHDENVER
=> Say "powered by DAOstack" in the footer of the DAO pages

src/components/Proposal/Create/CreateProposal.scss
Resolves: https://github.com/daostack/alchemy/issues/1423
=> fix new proposal checkbox styling

data/tokens.json
=> add curaDAI

src/components/Proposal/Create/SchemeForms/CreateSchemeRegistrarProposal.tsx
Resolves: https://github.com/daostack/alchemy/issues/1424
=> fix verbiage: scheme => plugin

src/settings.ts
Resolves: https://github.com/daostack/alchemy/issues/1453
=> fix WalletConnect

src/components/Proposal/Create/CreateProposal.scss, src/components/Proposal/Create/SchemeForms/CreateKnownGenericSchemeProposal.tsx, src/components/Proposal/Create/SchemeForms/CreateSchemeRegistrarProposal.tsx, src/components/Proposal/Create/SchemeForms/CreateUnknownGenericSchemeProposal.tsx, src/components/Scheme/ContributionRewardExtRewarders/Competition/Competitions.scss, src/components/Scheme/ContributionRewardExtRewarders/Competition/CreateSubmission.tsx
Resolves: https://github.com/daostack/alchemy/issues/1425
=> improve form validation error layout

src/components/Daos/Daos.scss, src/components/Daos/DaosPage.tsx
Also always show DAOs in the list that you follow even if they are not registered
=> Add search box to filter DAOs

src/components/Proposal/ProposalHistoryRow.tsx
Resolves: https://github.com/daostack/alchemy/issues/1337
=> in history, open proposal in new tab on ctrl-click

src/layouts/SidebarMenu.tsx
Resolves: https://github.com/daostack/alchemy/issues/684
=> show DAO total rep in sidebar

CHANGELOG.md, src/components/Daos/Daos.scss, src/components/Daos/DaosPage.tsx
* update changelog
* Tweak changelog
Co-authored-by: Tibet Sprague <tibetsprague@users.noreply.github.com>
=> release_20200303

package-lock.json, package.json, src/components/Proposal/Create/SchemeForms/MarkdownField.tsx
Fixes: https://github.com/daostack/alchemy/issues/964
=> In create proposal form tab directly from title to description

src/components/Account/Account.scss, src/components/Proposal/ActionButton.tsx, src/components/Proposal/Create/CreateProposalPage.tsx, src/components/Proposal/Create/SchemeForms/CreateUnknownGenericSchemeProposal.tsx, src/components/Proposal/Voting/VotersModal.scss, src/components/Proposal/Voting/VotersModal.tsx, src/components/Shared/ModalPopup.scss, src/components/Shared/ModalPopup.tsx, src/components/Shared/PreTransactionModal.scss, src/components/Shared/PreTransactionModal.tsx, src/components/Shared/SocialShareModal.scss, src/components/Shared/SocialShareModal.tsx, src/components/Shared/ThreeboxModal.scss, src/components/Shared/ThreeboxModal.tsx
Create ModalPopup component to bundle common modal stuff
Share common modal styles across all modals.
All ModalPopups can be closed by pressing esc or clicking on the background
All modals have a header, body and optional footer
=> Refactor modals

src/components/Shared/PreTransactionModal.tsx
Resolves: https://github.com/daostack/alchemy/issues/1480
=> don't show bar when not needed

CHANGELOG.md, src/components/Proposal/Create/SchemeForms/CreateUnknownGenericSchemeProposal.tsx, test/integration/proposal-genericScheme.ts
Resolves: https://github.com/daostack/alchemy/issues/1465
=> force validation of required fields in CreateUnknownGenericSchemeProposal

src/components/Dao/UnknownSchemeCard.scss, src/components/Dao/UnknownSchemeCard.tsx, src/components/Scheme/SchemeContainer.tsx, src/components/Scheme/SchemeInfoPage.tsx, src/lib/schemeUtils.ts
Fixes https://github.com/daostack/alchemy/issues/1210
=> Unknown schemes still link to Scheme page and show permissions

src/lib/schemeUtils.ts
Fixes https://github.com/daostack/alchemy/issues/1518
=> Fix display of an unknown scheme that has no name

src/components/DaoCreator/index.tsx
Closes https://github.com/daostack/alchemy/issues/1539
=> Fix Issue 1539

test/integration/rewards.ts
Resolves: https://github.com/daostack/alchemy/issues/1538
=> fixRewardsTest

CHANGELOG.md, package.json, src/arc.ts, src/assets/images/gear.svg, src/layouts/App.scss, src/layouts/Header.tsx, src/layouts/ProviderConfigButton.scss, src/layouts/ProviderConfigButton.tsx
Resolves: https://github.com/daostack/alchemy/issues/1540
=> add custom Torus configuration button

package-lock.json, package.json, src/components/DaoCreator/index.tsx
Closes https://github.com/daostack/alchemy/issues/1559
=> No DAOstack Logo

CHANGELOG.md
Need this before releasing 0.10.4
=> sync changelog with last-minute dev merges

src/settings.ts, src/subgraph_endpoints.json, webpack.dev.config.js, webpack.docker.config.js, webpack.prod.config.js
=> add subgraph_endpoints.json + hide infuraId

data/tokens.json
Fixes https://github.com/daostack/alchemy/issues/1599
=> Add CENNZ token on mainnet

src/layouts/SidebarMenu.tsx
Fixes https://github.com/daostack/alchemy/issues/1613
=> Change Get Involved link to point to https://daotalk.org/

CHANGELOG.md, src/components/Proposal/ProposalDetails.scss, src/components/Proposal/ProposalDetailsPage.tsx
Resolves: https://github.com/daostack/alchemy/issues/1085
=> support for embedded youtube and vimeo videos

src/components/Daos/DaosPage.tsx
Fixes https://github.com/daostack/alchemy/issues/1585
=> Fix duplicate DAOs when searching using capital characters

src/components/Daos/Daos.scss, src/components/Daos/DaosPage.tsx
Line up create button with right of the daos list.
Make search box font size smaller
Make the search box sticky
Improve how we handle stickiness
Get rid of empty space
Definitely check mobile!
Fixes https://github.com/daostack/alchemy/issues/1623
=> Tweak cosmetics of the DAOs page

src/settings.ts
Resolves: https://github.com/daostack/alchemy/issues/1604
=> xdai poa url should use wss

src/components/Proposal/Create/SchemeForms/CreateSchemeRegistrarProposal.tsx
=> show only register schemes in pluging manager

CHANGELOG.md, package-lock.json, package.json, src/settings.ts
xDAI:
- Remove burner connect (Not in use)
- add Tor.us
- use web3Modal 1.6.3
=> xDAI: Remove burner connect , Add Tor.us

src/components/Proposal/Create/CreateProposal.scss, src/components/Scheme/ContributionRewardExtRewarders/Competition/CreateProposal.tsx, src/components/Scheme/Scheme.scss
resolves: https://github.com/daostack/alchemy/issues/1676
=> fix Competition modal popup styling

CHANGELOG.md, src/components/Proposal/Create/CreateProposal.scss, src/components/Scheme/ContributionRewardExtRewarders/Competition/CreateProposal.tsx, src/components/Scheme/Scheme.scss, src/layouts/AppContainer.tsx
This is to catch dev up to the bug fixes in the release branch
=> Release 0.10.6 - to dev

src/components/Proposal/Voting/VoteButtons.tsx
till subgraph (or migration) issue will be solved https://github.com/daostack/subgraph/issues/548
=> temorary workaround for gh issue #1684

src/components/Proposal/Create/SchemeForms/CreateSchemeRegistrarProposal.tsx
Resolves: https://github.com/daostack/alchemy/issues/1673
=> add plugin to SchemeRegstrar plugins list

src/components/Dao/DaoSchemesPage.tsx, src/components/Scheme/SchemeProposalsPage.tsx
Resolves: https://github.com/daostack/alchemy/issues/1664
=> breadcrumbs for dao landing page, proposal plugins

CHANGELOG.md, README.md, docs/development.md, docs/nodocker.md, package-lock.json, package.json, scripts/serviceStatus.js
- bump package version
- update changelog
- Resolves: https://github.com/daostack/alchemy/issues/1695
=> Bump version and update changelog

src/assets/images/Icon/question-help.svg, src/components/Proposal/Create/CreateProposal.scss, src/components/Proposal/Create/SchemeForms/CreateContributionRewardProposal.tsx, src/components/Proposal/Create/SchemeForms/CreateKnownGenericSchemeProposal.tsx, src/components/Proposal/Create/SchemeForms/CreateSchemeRegistrarProposal.tsx, src/components/Proposal/Create/SchemeForms/CreateUnknownGenericSchemeProposal.tsx, src/components/Scheme/ContributionRewardExtRewarders/Competition/Competitions.scss, src/components/Scheme/ContributionRewardExtRewarders/Competition/CreateProposal.tsx, src/components/Scheme/ContributionRewardExtRewarders/Competition/CreateSubmission.tsx, src/components/Shared/HelpButton.scss, src/components/Shared/HelpButton.tsx
Resolves: https://github.com/daostack/alchemy/issues/1670
Note that to cover all the bases, this must be worked too:  https://github.com/daostack/alchemy/issues/1686
=> add help to proposal create description boxes

src/components/Proposal/ProposalDetails.scss, src/components/Proposal/ProposalDetailsPage.tsx
Resolves: https://github.com/daostack/alchemy/issues/1671
Resolves: https://github.com/daostack/alchemy/issues/1672
Also:  Fixes one case that was not detecting the vimeo video url (https://vimeo.com/412841518)
=> better embedded video UX

.travis.yml, package-lock.json, src/components/Proposal/Create/SchemeForms/CreateSchemeRegistrarProposal.tsx, src/lib/schemeUtils.ts
Fix "plugin manager" Edit scheme  permission ,for the case editing the "PluginManager" it self 
fix #1716
=> Fix plugin manage edit "plugin manager" scheme . permission

src/components/Dao/DaoLandingPage.tsx, src/components/Proposal/ProposalDetailsPage.tsx
Resolves: https://github.com/daostack/alchemy/issues/1701
Note that I was never able to reproduce this in staging.  Disqus doesn't work in the release review apps.
=> fix Disqus scoping

src/components/Scheme/SchemeContainer.tsx
Resolves: https://github.com/daostack/alchemy/issues/1709
=> fix new proposal button

src/components/Proposal/ProposalSummary/ProposalSummarySchemeRegistrar.tsx
Resolves: https://github.com/daostack/alchemy/issues/1715
=> show notification on copy to clipboard

src/components/Scheme/SchemeContainer.tsx
Resolves: https://github.com/daostack/alchemy/issues/1720
Resolves: https://github.com/daostack/alchemy/issues/1722
- fix edit button
- don't show new/edit buttons unless known proposal scheme
=> fix edit button, don't show new/edit buttons unless known scheme

src/assets/styles/global.scss
Resolves: https://github.com/daostack/alchemy/issues/1725
=> fix torus popup display problem

package-lock.json, package.json, src/components/Proposal/ProposalSummary/ProposalSummary.scss, src/components/Proposal/ProposalSummary/ProposalSummaryDutchX.tsx, src/components/Proposal/ProposalSummary/ProposalSummaryKnownGenericScheme.tsx, src/components/Proposal/ProposalSummary/ProposalSummaryUnknownGenericScheme.tsx, test/integration/wdio.conf.js
Resolves: https://github.com/daostack/alchemy/issues/1732
=> warn when GenericScheme `value` is > 0

src/components/Feed/ProposalFeedItem.tsx, src/components/Proposal/ProposalDetails.scss, src/components/Proposal/ProposalDetailsPage.tsx, src/components/Scheme/ContributionRewardExtRewarders/Competition/Competitions.scss, src/components/Scheme/ContributionRewardExtRewarders/Competition/CreateProposal.tsx, src/components/Scheme/ContributionRewardExtRewarders/Competition/CreateSubmission.tsx, src/components/Scheme/ContributionRewardExtRewarders/Competition/Details.tsx, src/components/Scheme/ContributionRewardExtRewarders/Competition/SubmissionDetails.tsx, src/components/Shared/ProposalDescription.scss, src/components/Shared/ProposalDescription.tsx
Resolves: https://github.com/daostack/alchemy/issues/1686
Note this doesn't do bounties (see ticket)
=> embed videos everywhere

src/components/Dao/ProposalSchemeCard.tsx
Resolves: https://github.com/daostack/alchemy/issues/1739
=> order top 3 proposals by boostedAt

src/components/Shared/PreTransactionModal.scss, src/components/Shared/PreTransactionModal.tsx
Resolves: https://github.com/daostack/alchemy/issues/1629
Also fixes this:
=> fix stake amount GEN label

src/components/Proposal/ActionButton.scss, src/components/Proposal/ActionButton.tsx, src/components/Redemptions/RedemptionsButton.tsx, src/components/Redemptions/RedemptionsMenu.scss, src/components/Redemptions/RedemptionsPage.scss
Resolves: https://github.com/daostack/alchemy/issues/1711
Resolves: https://github.com/daostack/alchemy/issues/1745
Resolves: https://github.com/daostack/alchemy/issues/1549
=> make redemptions UI respond to changing state

src/components/Dao/DaoLandingPage.tsx
Resolves: https://github.com/daostack/alchemy/issues/1693
Note the review app is running against xdai.
=> sosCollective Landing Page

src/components/Account/AccountProfilePage.tsx, src/components/Proposal/Voting/VotersModal.tsx
Resolves: https://github.com/daostack/alchemy/issues/1596
=> load voter profiles in VotersModal

src/components/Proposal/Create/CreateProposalPage.tsx, src/components/Proposal/Create/SchemeForms/CreateContributionRewardProposal.tsx, src/components/Scheme/ContributionRewardExtRewarders/Competition/CreateSubmission.tsx, src/components/Scheme/ContributionRewardExtRewarders/Competition/Details.tsx, src/components/Shared/UserSearchField.tsx
Resolves: https://github.com/daostack/alchemy/issues/1667
=> default user account when creating CR proposal

src/components/Scheme/ContributionRewardExtRewarders/Competition/Competitions.scss, src/components/Scheme/ContributionRewardExtRewarders/Competition/CreateProposal.tsx, src/components/Scheme/ContributionRewardExtRewarders/Competition/CreateSubmission.tsx, src/components/Scheme/ContributionRewardExtRewarders/Competition/Details.tsx, src/lib/proposalUtils.ts
Resolves: https://github.com/daostack/alchemy/issues/1656
=> url params for Competitions/Submissions

src/components/Shared/Countdown.tsx, src/components/Shared/ProposalCountdown.tsx, src/lib/util.ts
Resolves: https://github.com/daostack/alchemy/issues/1763
=> fix count of days in countdowns

src/components/Daos/Daos.scss, src/components/Daos/DaosPage.tsx, src/layouts/App.scss, src/layouts/SidebarMenu.scss, src/layouts/SidebarMenu.tsx
All these are intimately related and dependent:
Resolves: https://github.com/daostack/alchemy/issues/1640
Resolves: https://github.com/daostack/alchemy/issues/1726
Resolves: https://github.com/daostack/alchemy/issues/1612
Resolves: https://github.com/daostack/alchemy/issues/1760
=> fix All Daos page layout problems

src/components/Proposal/Voting/VoteBreakdown.scss
Resolves: https://github.com/daostack/alchemy/issues/1628
=> fix historic display of voting percentages

src/components/Proposal/ProposalDetailsPage.tsx, src/components/Scheme/ContributionRewardExtRewarders/DetailsPageRouter.tsx
Resolves: https://github.com/daostack/alchemy/issues/1744
=> validateDaoProposalRoute

src/components/Dao/DaoLandingPage.scss
Resolves: https://github.com/daostack/alchemy/issues/1773
Only affects DAO landing page.  Other pages need attention which should be done in a separate PR.
=> give dao landing page padding on mobile

src/components/Scheme/SchemeContainer.tsx, src/components/Scheme/SchemeProposalsPage.tsx
Resolves: https://github.com/daostack/alchemy/issues/1781
=> remove redundant New Proposal button

src/components/Proposal/ProposalDetails.scss, src/components/Proposal/Voting/VoteButtons.scss, src/components/Proposal/Voting/VoteButtons.tsx
Resolves: https://github.com/daostack/alchemy/issues/1771
=> line up votingDisabled text

src/components/Proposal/Create/SchemeForms/CreateSchemeRegistrarProposal.tsx, src/components/Scheme/SchemeInfoPage.tsx
Resolves: https://github.com/daostack/alchemy/issues/1765
=> augment mintBurnReputation permission description

.gitignore, src/layouts/SidebarMenu.scss, src/layouts/SidebarMenu.tsx
Resolves: https://github.com/daostack/alchemy/issues/1753
Resolves: https://github.com/daostack/alchemy/issues/1792
Resolves: https://github.com/daostack/alchemy/issues/1802
* has min height at three currencies.  In other words, max of three currencies will always be visible without showing a scroll bar.
* required some code refactoring, needed anyways.  big improvement.
Check on mobile too.
Check with too many tokens and with <= 3.
With too many:
With exactly three:
=> improve sidebar scroll, fix DAOstack icon color

.eslintrc, src/components/Proposal/ActionButton.tsx, src/components/Redemptions/RedemptionsMenu.tsx
Resolves: https://github.com/daostack/alchemy/issues/1776
=> close Redemptions menu on Redeem click

src/components/Account/Account.scss, src/components/Account/AccountProfilePage.tsx, src/components/Shared/SocialShareModal.tsx
Resolves: https://github.com/daostack/alchemy/issues/1729
Looks like this now:
And this:
Now looks like this:
=> improve layout of AccountProfile popup

src/components/Dao/DaoHistoryPage.tsx, src/components/Dao/DaoMembersPage.tsx, src/components/Daos/DaosPage.tsx, src/components/Feed/FeedPage.tsx, src/components/Scheme/SchemeProposalsPage.tsx
Resolves: https://github.com/daostack/alchemy/issues/1752
=> removed all cases of dash at end of infinitescroll

src/components/Shared/ProposalDescription.tsx
Repro the exception by visiting this proposal:
https://alchemy.daostack.io/dao/0x15344ecdc2c4edfcb092e284d93c20f0529fd8a6/proposal/0x69e398e216c60e42b3efa2d533566187b3c527dd48574a13a1c50a7b63eccaf5
The URL that's causing the exception is this email: notices@dorg.tech
=> Bug Fix: Handle Invalid URL Exception

src/components/Scheme/SchemeInfo.scss, src/components/Scheme/SchemeInfoPage.tsx
Resolves: https://github.com/daostack/alchemy/issues/1785
- Major improvement is on mobile.  Has side-effects of improvements at various widths on desktop too
- Part of the solution is adding ellipses to the params hash
- improves the code, ditching the table, vastly facilitating responsive coding
=> improve scheme info layout

package-lock.json, package.json, src/components/Proposal/Create/SchemeForms/CreateKnownGenericSchemeProposal.tsx, src/components/Scheme/ContributionRewardExtRewarders/rewardersProps.ts, src/genericSchemeRegistry/schemes/ENSPublicResolver.json, src/genericSchemeRegistry/schemes/ENSRegistry.json, src/lib/schemeUtils.ts, src/lib/util.ts, test/integration/proposal-genericSchemeDutchx.ts, test/integration/proposal-genericSchemeEnsPublicResolver.ts, test/integration/proposal-genericSchemeEnsRegistry.ts, test/integration/proposal-genericSchemeRegistryLookup.ts, test/integration/wdio-headless.conf.js, webpack.prod.config.js
Resolves: https://github.com/daostack/alchemy/issues/1766
Resolves: https://github.com/daostack/alchemy/issues/1789
Resolving the 1789 was necessary because splitting camel casing wasn't working right.
But need to confirm that splitting camel-casing is what we want.  We've always been doing it.  It will now be more apparent.
=> use contract alias for plugin name

src/lib/schemeUtils.ts
Address: https://github.com/daostack/alchemy/pull/1818/files#r439872881
=> don't split GenericScheme name

src/components/Scheme/SchemeContainer.tsx
Resolves: https://github.com/daostack/alchemy/issues/1810
=> fix proposal count not updating

src/arc.ts, src/lib/util.ts, test/integration/wdio.conf.js
Resolves: https://github.com/daostack/alchemy/issues/1813
=> fix arc.InTesting

src/components/Proposal/Create/PluginForms/PluginInitializeFields.tsx, src/components/Proposal/Create/PluginForms/Validators.ts, src/components/Proposal/ProposalSummary/ProposalSummaryPluginManager.tsx
=> Added validation of GP parameters

src/components/Proposal/Create/PluginForms/CreatePluginManagerProposal.tsx, src/lib/util.ts
Added util function to convert a Date object to posix time.
Activation time input is now converted from Date object to posix time..
fix #1833
=> Activation time is now converted from Date object to posix time

src/components/Proposal/ProposalSummary/ProposalSummaryPluginManager.tsx, src/lib/pluginUtils.ts
When creating a new plugin, if the plugin type is "ContributionRewardExt" the real name is extracted from the decoded pluginToRegisterData.
=> Decode pluginToRegisterData and extract the real plugin name 

.travis.yml, src/components/Proposal/Create/PluginForms/CreatePluginManagerProposal.tsx
When creating a proposal, activation time is now given a default date for the same hour the next day.
=> Added default future date for activation time

src/components/Proposal/Create/PluginForms/CreatePluginManagerProposal.tsx, test/integration/plugin-manager.ts, test/integration/utils.ts
- Added new generic function to submit a form.
- Added a new robust function to accept cookies. I'll open another PR if I'll see that the new one can replace the old one with no issues.
=> Added plugin manager autotest

src/components/Proposal/ProposalSummary/ProposalSummaryKnownGenericScheme.tsx
Resolves: https://github.com/daostack/alchemy/issues/1882
=> fix copy to clipboard for callData array params

data/tokens.json
This PR is needed for a proposal within i4 Art DAO, the sooner we can get this the better :) 
Thanks!
cc @EzraWeller
=> Add the GEMS token to the new proposal token list, for i4

README.md, src/components/Dao/DaoLandingPage.scss, src/components/Dao/DaoLandingPage.tsx, src/customDaoInfo.tsx
Resolves: https://github.com/daostack/alchemy/issues/1858
- Also moves all custom DAO data into a separate file.  This file is a tsx file to allow the content to contain react components.
- Has this unresolved question:  https://github.com/daostack/alchemy/issues/1858#issuecomment-648484206.  I settled on "The Venus Project", hot, of course.  @EzraWeller 
- adds presumption that a DAO's address cannot be presumed unique across networks.
=> custom landing page for the Venus Project

src/components/Proposal/ProposalDetails.scss, src/components/Proposal/ProposalDetailsPage.tsx, src/components/Proposal/Staking/StakeButtons.scss, src/components/Proposal/Staking/StakeButtons.tsx, src/components/Proposal/Voting/VoteButtons.scss, src/components/Proposal/Voting/VoteButtons.tsx
Resolves: https://github.com/daostack/alchemy/issues/1844
- another case of absolute positioning causing problems.  So I refactored some code
- also looks good in the proposal card popup:
- This:
becomes:
- This: 
becomes:
=> fix no rep when created message

src/layouts/SidebarMenu.tsx, src/lib/util.ts
Address https://github.com/daostack/alchemy/pull/1921#pullrequestreview-443419386.  While fixing every other use case, I didn't fix the one that was actually requested in [the original ticket](https://github.com/daostack/alchemy/issues/1904).
Note: The review app is pointing to xDAI.
=> fix DaoHoldings link on xDAI

data/tokens.json
=> Added DXdao (DXD) Token

CHANGELOG.md, src/components/Dao/DaoLandingPage.tsx
Resolves: https://github.com/daostack/alchemy/issues/1943
Note this is already fixed in 2.0
=> fix access to DAOs on ganache

src/components/Proposal/Create/SchemeForms/CreateKnownGenericSchemeProposal.tsx, src/components/Proposal/Create/SchemeForms/CreateUnknownGenericSchemeProposal.tsx
Resolves: https://github.com/daostack/alchemy/issues/1942
Note this is already fixed in 2.0
=> fix description label bugs

src/assets/styles/global-variables.scss, src/components/Dao/DaoPluginsPage.scss, src/components/Daos/Daos.scss, src/components/Daos/DaosPage.tsx, src/components/Plugin/Plugin.scss
resolves: https://github.com/daostack/alchemy/issues/1950 and resolves: https://github.com/daostack/alchemy/issues/1938
- New color to "Add Proposal" and "Add a Plugin" buttons.
- Added label next to envelope icon
=> Simple UX changes

src/components/Dao/DaoSchemesPage.tsx, src/lib/schemeUtils.ts
Resolves: https://github.com/daostack/alchemy/issues/1888
The review app is pointing to mainnet since the repo cases given in the ticket are pointing there.
=> don't crash when no PluginManager

src/components/Proposal/Create/PluginForms/PluginInitializeFields.tsx
resolves: https://github.com/daostack/alchemy/issues/1957
=> kovan: fixed no Custom Contract To Call field at plugin manager

src/actions/arcActions.ts
Resolves: https://github.com/daostack/alchemy/issues/1967https://github.com/daostack/alchemy/issues/1967
=> at least execute if can't redeem

data/tokens.json
=> Added DMG token

package-lock.json, src/lib/util.ts
Resolves: https://github.com/daostack/alchemy/issues/1963
=>  poll per 60 seconds for eth/token balances

src/lib/util.ts
Resolves: https://github.com/daostack/alchemy/issues/1969https://github.com/daostack/alchemy/issues/1969 for Alchemy 1.0
=> fix computation of GEN available for staking - 1.0

src/lib/util.ts
Resolves: https://github.com/daostack/alchemy/issues/1969https://github.com/daostack/alchemy/issues/1969
=> fix computation of GEN available for staking

CHANGELOG.md, package-lock.json, package.json
=> changelog, bump version

src/components/Plugin/ContributionRewardExtRewarders/Competition/Details.tsx, src/components/Plugin/ContributionRewardExtRewarders/DetailsPageRouter.tsx, src/components/Plugin/ContributionRewardExtRewarders/rewardersProps.ts, src/lib/pluginUtils.ts
Resolves: https://github.com/daostack/alchemy/issues/1986
Resolves: https://github.com/daostack/alchemy/issues/1989
=> fixCrashOnCompetitionDetails

package-lock.json, package.json, src/actions/arcActions.ts, src/components/Proposal/ActionButton.tsx
Resolves: https://github.com/daostack/alchemy/issues/1993
=> Fix Analytics failure ; Fix redeem issue

src/components/Proposal/ProposalDetailsPage.tsx
resolves: https://github.com/daostack/alchemy/issues/2006
Old:
New:
=> Predictions UI fix

src/arc.ts, src/lib/util.ts
Resolves: https://github.com/daostack/alchemy/issues/1978
=> fix computation of networkId

src/components/Daos/Daos.scss
resolves: https://github.com/daostack/alchemy/issues/2022
=> fix text location in daos search input on Safari

package-lock.json, package.json
resolves: #2009
@orenyodfat @cbrzn See comments from the old PR https://github.com/daostack/alchemy/pull/2010
=> bump daocreator version - 2

src/arc.ts, test/integration/daos.ts, test/integration/feed.ts, test/integration/history.ts, test/integration/members.ts, test/integration/profile.ts, test/integration/proposal-genericPluginStandardBounties.ts, test/integration/rewards.ts, test/integration/utils.ts, test/integration/wdio.conf.js
Resolves: https://github.com/daostack/alchemy/issues/2008
=> add goToUrl and in it set inAlchemyTests

src/assets/styles/global-variables.scss, src/components/Dao/PluginCard.scss
resolves: https://github.com/daostack/alchemy/issues/2027
=> Fix hover border location ; Using global variable for border color

src/components/Plugin/PluginContainer.tsx
resolves: https://github.com/daostack/alchemy/issues/2032
=> Edit plugin redirects to replace tab

src/genericSchemeRegistry/README.md
Resolves: https://github.com/daostack/alchemy/issues/2035
=> expand genericscheme docs

.github/ISSUE_TEMPLATE/bug_report.md, src/layouts/Header.tsx, typings/build.d.ts, webpack.base.config.js
Resolves: https://github.com/daostack/alchemy/issues/1900
Just like https://github.com/daostack/alchemy/pull/1977, but for 1.0
=> expose app version - 1.0

src/components/Proposal/ProposalSummary/ProposalSummaryCO2ken.tsx, src/components/Proposal/ProposalSummary/ProposalSummaryDutchX.tsx, src/components/Proposal/ProposalSummary/ProposalSummaryKnownGenericScheme.tsx, src/components/Proposal/ProposalSummary/ProposalSummaryStandardBounties.tsx
Responds to: https://github.com/daostack/alchemy/issues/2021
**Review app is pointing at mainnet**
Reproducible here for KnownGenericPlug:  https://alchemy-showrawcalldata-v1qd6d.herokuapp.com/dao/0x519b70055af55a007110b4ff99b0ea33071c720a/proposal/0x862664cdf95643102bdd92f50d5ece479f09bea43904afb3e2d7bee287dcbfa5
=> show raw calldata (1.0)

.github/ISSUE_TEMPLATE/bug_report.md, CHANGELOG.md, package-lock.json, package.json, src/components/DaoCreator/index.tsx, src/components/Proposal/ProposalSummary/ProposalSummaryCO2ken.tsx, src/components/Proposal/ProposalSummary/ProposalSummaryDutchX.tsx, src/components/Proposal/ProposalSummary/ProposalSummaryKnownGenericScheme.tsx, src/components/Proposal/ProposalSummary/ProposalSummaryStandardBounties.tsx, src/genericSchemeRegistry/README.md, src/layouts/Header.tsx, typings/build.d.ts, webpack.base.config.js
* bump tp 0.10.14
* update changelog
* fix typo
=> release 0.10.14

src/lib/pluginUtils.ts
Resolves: https://github.com/daostack/alchemy/issues/2050
Fixes only the crash part of that ticket. Does not address the other part which is only user error.
You can test it on rinkeby here:  /dao/0xba09811d02631d1b03c21d1369cfcba42348738e/plugins/
=> fix display of unknown plugins

CHANGELOG.md, package-lock.json, package.json, src/subgraph_endpoints.json
=> revert subgraph endpoint domain

CHANGELOG.md, src/components/Proposal/ProposalDetails.scss, src/components/Proposal/ProposalDetailsPage.tsx, src/lib/util.ts
Resolves https://github.com/daostack/alchemy/issues/2053
for 1.0
I have done the simplest thing.  If you want more, please comment [here in the ticket](https://github.com/daostack/alchemy/issues/2053#issuecomment-673547012)
=> display proposal event history

CHANGELOG.md, src/components/Proposal/ProposalDetailsPage.tsx
Resolves: https://github.com/daostack/alchemy/issues/2057  for 1.0
=> automatically refresh voting status

.travis.yml, package-lock.json, package.json, test/integration/wdio.conf.js
resolves: https://github.com/daostack/alchemy/issues/2092
=> Updated chrome driver for tests

src/assets/locales/en/translation.json, src/components/Plugin/Plugin.scss, src/components/Plugin/PluginContainer.tsx, src/components/Proposal/ProposalSummary/ProposalSummary.tsx, src/components/Proposal/ProposalSummary/ProposalSummaryFundingRequest.tsx, src/components/Proposal/ProposalSummary/ProposalSummaryJoin.tsx, src/lib/pluginUtils.ts
resolves: https://github.com/daostack/alchemy/issues/1954
resolves: https://github.com/daostack/alchemy/issues/1955
resolves: https://github.com/daostack/alchemy/issues/2086
Creation of Join and FundingRequest proposals are temporarily disabled until they will be available.
=> Support for Join and FundingRequest plugins (proposals are read only)

src/subgraph_endpoints.json
resolves: https://github.com/daostack/alchemy/issues/2107
=> Update subgraph endpoints to v8_12

package-lock.json, package.json
resolves: https://github.com/daostack/alchemy/issues/2112
=> Updated daocreator version

src/components/Proposal/Create/PluginForms/CreatePluginManagerProposal.tsx
Resolves: https://github.com/daostack/alchemy/issues/2115
=> fix plugin manager new proposal params

src/components/Daos/Daos.scss, src/layouts/App.scss
resolves: https://github.com/daostack/alchemy/issues/2101
=> Fix bad ui when using autocomplete input in chrome

src/components/Proposal/Voting/VoteButtons.scss
resolves: https://github.com/daostack/alchemy/issues/2117
=> fix misplaced against vote button

src/components/Proposal/ProposalDetails.scss, src/components/Proposal/Voting/VoteBreakdown.scss
resolves: https://github.com/daostack/alchemy/issues/2063
=> Fix vote feedback alignment

src/components/Proposal/ProposalSummary/ProposalSummaryPluginManager.tsx
resolves: https://github.com/daostack/alchemy/issues/2116
=> Fix wrong plugin name

.travis.yml, package-lock.json, package.json
resolves: https://github.com/daostack/alchemy/issues/2131
=> Update travis.yml to run test coverage

data/tokens.json
Resolves: https://github.com/daostack/alchemy/issues/2098
=> add PAN Token on mainnet

package-lock.json, package.json
Resolves: https://github.com/daostack/alchemy/issues/2090
Upgrades arc.js to 0.2.73
=> add Redeemer contract for Kovan

src/components/Daos/DaosPage.tsx
Resolves: https://github.com/daostack/alchemy/issues/1905
=> don't show email button on xDAI

src/components/Proposal/Staking/StakeButtons.tsx, src/components/Proposal/Voting/VoteButtons.tsx
Resolves: https://github.com/daostack/alchemy/issues/2119
Removes the offending message entirely.  Same for staking button message.
=> remove vote/staking status message on executed proposals

src/components/Proposal/Create/CreateProposal.scss
resolves: https://github.com/daostack/alchemy/issues/2134
=> Fix no side bar modal scrolling

src/components/Account/AccountBalances.tsx, src/components/Account/AccountProfilePage.tsx, src/layouts/App.scss, test/integration/profile.ts
Resolves: https://github.com/daostack/alchemy/issues/1915
Refactors the CSS
=> show holdings when no DAO

package-lock.json, package.json, src/components/Account/AccountBalances.tsx, src/components/Account/AccountProfilePage.tsx, src/components/Dao/DaoContainer.tsx, src/components/Dao/DaoHistoryPage.tsx, src/components/Dao/DaoPluginsPage.tsx, src/components/Dao/ProposalPluginCard.tsx, src/components/Daos/DaosPage.tsx, src/components/Plugin/ContributionRewardExtRewarders/Competition/Details.tsx, src/components/Plugin/ContributionRewardExtRewarders/Competition/List.tsx, src/components/Plugin/ContributionRewardExtRewarders/Competition/utils.ts, src/components/Plugin/ContributionRewardExtRewarders/DetailsPageRouter.tsx, src/components/Plugin/PluginContainer.tsx, src/components/Plugin/PluginProposalsPage.tsx, src/components/Proposal/ActionButton.tsx, src/components/Proposal/ProposalCard.tsx, src/components/Proposal/ProposalData.tsx, src/components/Proposal/ProposalDetailsPage.tsx, src/components/Proposal/RedemptionsString.tsx, src/components/Proposal/RedemptionsTip.tsx, src/components/Redemptions/RedemptionsButton.tsx, src/components/Redemptions/RedemptionsMenu.tsx, src/components/Redemptions/RedemptionsPage.tsx, src/components/Shared/PreTransactionModal.tsx, src/layouts/Header.tsx, src/layouts/SidebarMenu.tsx, src/settings.ts, test/integration/wdio.conf.js
resolves: https://github.com/daostack/alchemy/issues/2126 - for 2.0
resolves: https://github.com/daostack/alchemy/issues/2049
- **Creating proposals**, **voting** and **redeeming** are reflected in the UI automatically
- **Staking** and **number of Regular Proposals, Pending Boosting and Boosted Proposals** are still not reflected in the UI (need to refresh the page to see)
**UPDATE:** proposals counters are now fixed.
**UPDATE:** staking data is now updated automatically
=> Update arc.js 56 ; use polling

src/components/Proposal/Create/PluginForms/CreatePluginManagerProposal.tsx, src/components/Proposal/Create/PluginForms/PluginInitializeFields.tsx
resolves: https://github.com/daostack/alchemy/issues/2135
=> Support Join and FundingRequest creation in PluginManager

package-lock.json, package.json, src/components/Account/AccountBalances.tsx, src/components/Account/AccountProfilePage.tsx, src/components/Dao/DaoContainer.tsx, src/components/Dao/DaoHistoryPage.tsx, src/components/Dao/DaoSchemesPage.tsx, src/components/Dao/ProposalSchemeCard.tsx, src/components/Daos/DaosPage.tsx, src/components/Proposal/Create/SchemeForms/TagsSelector.tsx, src/components/Proposal/ProposalData.tsx, src/components/Proposal/ProposalDetailsPage.tsx, src/components/Proposal/Voting/VotersModal.tsx, src/components/Redemptions/RedemptionsButton.tsx, src/components/Redemptions/RedemptionsMenu.tsx, src/components/Redemptions/RedemptionsPage.tsx, src/components/Scheme/ContributionRewardExtRewarders/Competition/Details.tsx, src/components/Scheme/ContributionRewardExtRewarders/Competition/List.tsx, src/components/Scheme/ContributionRewardExtRewarders/Competition/utils.ts, src/components/Scheme/ContributionRewardExtRewarders/DetailsPageRouter.tsx, src/components/Scheme/SchemeContainer.tsx, src/components/Scheme/SchemeProposalsPage.tsx, src/layouts/Header.tsx, src/layouts/SidebarMenu.tsx, src/lib/util.ts, src/settings.ts
Resolves: https://github.com/daostack/alchemy/issues/2126 for 1.0
=> introduce polling

data/tokens.json, src/genericSchemeRegistry/schemes/Api3Token.json, src/genericSchemeRegistry/schemes/TimelockManager.json
Adds two GenericScheme plugins for Rinkeby:
* Api3Token
* TimelockManager
Adds the API3 token to *Funding and Voting Power* for Rinkeby
=> Add API3 DAO GenericScheme plugins for Rinkeby

.travis.yml, package.json
Resolves: https://github.com/daostack/alchemy/issues/2152
=> update node.js version

src/components/Daos/DaosPage.tsx
resolves: https://github.com/daostack/alchemy/issues/2160
=> Show all registered daos when SHOW_ALL_DAOS is set to false

data/tokens.json
Adds PINC token on xDAI for PrimeDAO
https://blockscout.com/poa/xdai/tokens/0x42f863Ee29eaf48563EDCB553e66B3CEe406851B/token-transfers
The DAO:  https://alchemy-2-xdai.herokuapp.com/dao/0xe3a89ed4956c4f7173418e4dec2a77a5f60807de
=> add PINC token

src/layouts/SidebarMenu.scss, src/layouts/SidebarMenu.tsx
resolves: https://github.com/daostack/alchemy/issues/2172
=> Significant improvement for DAO name styles

.travis.yml, package.json, src/assets/locales/en/translation.json, src/assets/styles/global-variables.scss, src/components/Plugin/ContributionRewardExtRewarders/Competition/CreateProposal.tsx, src/components/Proposal/Create/CreateProposal.scss, src/components/Proposal/Create/PluginForms/ABIService.ts, src/components/Proposal/Create/PluginForms/CreatePluginManagerProposal.tsx, src/components/Proposal/Create/PluginForms/CreateUnknownGenericPluginProposal.tsx, src/components/Proposal/Create/PluginForms/PluginInitializeFields.tsx, src/components/Proposal/ProposalSummary/ProposalSummaryUnknownGenericPlugin.tsx, src/components/Shared/Loading.scss, src/components/Shared/SelectSearch.scss, src/components/Shared/SelectSearch.tsx, test/integration/proposal-genericPlugin.ts
resolves: https://github.com/daostack/alchemy/issues/2150
resolves: https://github.com/daostack/alchemy/issues/2156
resolves: https://github.com/daostack/alchemy/issues/2174
**Note** (not relevant any more): In the test - for some strange reason I couldn't set the activation time of a plugin, so for now I changed the future activation time to be current time + 10 seconds (instead of +24 hours)
- We can leave it like this (+10 seconds future time instead of +24 hours)
- Keep investigate the issue
- Try to change the code of the calendar and use different one
- Add a plugin to test env that supports a blockchain interaction plugin with a contract to call that has an ABI data.
**UPDATE**: using now the React date picker as used in other places in Alchemy which is much more stable and …
=> Support blockchain interaction ABI calldata

package-lock.json, package.json, src/layouts/SidebarMenu.scss, src/layouts/SidebarMenu.tsx, webpack.base.config.js
Adds the links spec'd here: https://github.com/daostack/alchemy/issues/2178, for 1.0
bumps package version to 1.0.0
=> add new sidebar links - 1.0

package-lock.json, package.json, src/layouts/SidebarMenu.scss, src/layouts/SidebarMenu.tsx, webpack.base.config.js
Adds the links spec'd here: https://github.com/daostack/alchemy/issues/2178, for 2.0
Bumps package version to 2.0.0
=> add new sidebar links - 2.0

src/assets/styles/global-variables.scss, src/components/Dao/Dao.scss, src/components/Dao/DaoContainer.tsx, src/components/Daos/Daos.scss, src/layouts/App.scss, src/layouts/Header.tsx, src/layouts/SidebarMenu.scss
Resolves: https://github.com/daostack/alchemy/issues/2178
=> alchemy banner message

data/tokens.json, src/components/Proposal/ActionButton.tsx
bugs found while investigating the PrimeDAO redeeming bug
=> lowercase tokens, proposalState to RedemptionsTip

src/components/Dao/DaoHistoryPage.scss, src/components/Dao/DaoHistoryPage.tsx, src/components/Proposal/ProposalHistoryRow.scss, src/components/Proposal/ProposalHistoryRow.tsx
https://github.com/daostack/alchemy/issues/2175 on 1.0
=> add in progress label in history - 1.0

src/components/Proposal/Create/PluginForms/PluginInitializeFields.tsx, test/integration/proposal-genericPlugin.ts
resolves: https://github.com/daostack/alchemy/issues/1982
=> Unique IDs

src/components/Proposal/ProposalCard.tsx
resolve: https://github.com/daostack/alchemy/issues/2201
=> Fix missing pre-boost button on a proposal card

src/components/Plugin/PluginContainer.tsx, src/components/Proposal/Create/PluginForms/CreatePluginManagerProposal.tsx
Also fixes an issue where Alchemy crashes if you go to a plugin registrar that is not yet activated.
=> Updated permissions

package-lock.json, package.json, src/components/Proposal/Create/PluginForms/CreatePluginManagerProposal.tsx, src/components/Proposal/ProposalSummary/ProposalSummaryPluginManager.tsx, test/integration/proposal-genericPlugin.ts
resolves: https://github.com/daostack/alchemy/issues/2218
- adjustments to arc.js to work with string[] voting params
- some parameters to be sent as wei in plugin manager
Depends on https://github.com/daostack/arc.js/pull/559
=> Adjustments to arc.js

src/arc.ts, src/components/Shared/withSubscription.tsx
resolves: https://github.com/daostack/alchemy/issues/2231 for 2.0
=> Avoid crashing Alchemy when there is no network or The Graph servers are overloaded - 2.0

src/arc.ts, src/components/Shared/withSubscription.tsx
resolves: https://github.com/daostack/alchemy/issues/2231 for 1.0
=> Avoid crashing Alchemy when there is no network or The Graph servers are overloaded - 1.0

src/arc.ts, src/lib/proposalUtils.ts
resolves: https://github.com/daostack/alchemy/issues/2238
=> Fix modal service nesting ; remove unnecessary console log

src/components/Scheme/ContributionRewardExtRewarders/Competition/List.tsx, src/lib/schemeUtils.ts
=> Fix competition tab crash ; Fix compitition plugin ugly name

src/components/Proposal/Create/SchemeForms/ABIService.ts, src/components/Proposal/Create/SchemeForms/CreateGenericMultiCallProposal.tsx, src/components/Proposal/Create/SchemeForms/Validators.ts, src/components/Proposal/ProposalSummary/ProposalSummaryMultiCallGenericScheme.tsx, src/components/Scheme/SchemeInfoPage.tsx, webpack.dev.config.js, webpack.docker.config.js, webpack.prod.config.js
resolves: https://github.com/daostack/alchemy/issues/2255
=> Support method arrays params in generic multi-call

src/layouts/SidebarMenu.tsx
=> feat: add link xGEN --> GEN

src/components/Proposal/ProposalDetailsPage.tsx
resolves: https://github.com/daostack/alchemy/issues/2263
=> Fix wrong share link

package-lock.json, package.json
resolves: https://github.com/daostack/alchemy/issues/2280
=> Fix 3box following issue

src/components/Scheme/SchemeInfoPage.tsx
resolves:  https://github.com/daostack/alchemy/issues/2283
=> Show GP params in competition scheme

src/components/Notification/Notification.scss, src/layouts/App.scss
This PR fix issue with positioning of 'X' on notifications; per #1811
=> #1811 - fixed styling of notifications message modal

src/assets/styles/global-variables.scss, src/components/Dao/DaoLandingPage.scss, src/components/Dao/DaoLandingPage.tsx, src/components/Notification/Notification.scss, src/layouts/App.scss
Implemented logic to use colours from global
=> Fixed colours to use them from global CSS

src/components/Dao/DaoContainer.tsx
=> fix member+following daos list

src/subgraph_endpoints.json
resolves: https://github.com/daostack/alchemy/issues/2300
=> update subgraph v41_1

package-lock.json, package.json
resolves: https://github.com/daostack/alchemy/issues/2309
=> Update daocreator v1.0.21

src/layouts/SidebarMenu.scss, test/integration/proposal-genericSchemeDutchx.e2e.ts
resolves: https://github.com/daostack/alchemy/issues/2306
=> Fix banner overlaps

src/components/Dao/DaoProposalsPage.tsx, src/components/Redemptions/RedemptionsPage.tsx, src/subgraph_endpoints.json, test/integration/proposal-genericSchemeEnsRegistry.e2e.ts
resolves: https://github.com/daostack/alchemy/issues/2326
Sort proposals by the next order: executables, passing and falling by `closingAt` in ascending order, and then failed and executed proposals.
=> Sort Proposals

src/components/Proposal/Create/SelectProposal/SelectProposal.scss
resolves: https://github.com/daostack/alchemy/issues/2324 (part of it)
=> add box shadow to schemes select

src/components/Account/Account.scss, src/components/Dao/Dao.scss, src/components/Dao/DaoContainer.tsx, src/components/Dao/DaoProposalsPage.scss, src/components/Dao/DaoProposalsPage.tsx, src/components/Daos/Daos.scss, src/components/Daos/DaosPage.tsx, src/components/Proposal/ActionButton.scss, src/components/Proposal/Create/CreateProposalPage.tsx, src/components/Redemptions/RedemptionsMenu.tsx, src/components/Redemptions/RedemptionsPage.tsx, src/components/Shared/ModalPopup.scss, src/components/Shared/ModalPopup.tsx, src/components/Shared/PreTransactionModal.tsx, src/layouts/App.scss, src/layouts/AppContainer.tsx, src/layouts/Header.tsx, src/layouts/SidebarMenu.scss, src/lib/proposalHelpers.ts
See Ezra's comments here: https://github.com/daostack/alchemy/pull/2340#issuecomment-745578151
Resolves: (3) (7.2) (8) (13) (9)
=> Some release 1.0.4 issues

src/components/Proposal/ProposalDetails.scss
resolves: https://github.com/daostack/alchemy/issues/2355
=> Fix proposal long content with html code tag

package-lock.json, package.json, src/lib/util.ts
=> update web3 to 1.3.1

src/components/Proposal/ProposalRow.tsx
No need to show proposal countdown (00:00:00:00) for Executable, Executed and Failed proposals.
=> Show proposal countdown only if it's not 0

src/arc.ts, src/components/Proposal/Create/CreateProposalPage.tsx, src/components/Proposal/Create/SchemeForms/ABIService.ts, src/components/Proposal/Create/SchemeForms/CreateGenericMultiCallProposal.tsx, src/components/Proposal/ProposalSummary/ProposalSummary.tsx, src/components/Proposal/ProposalSummary/ProposalSummaryMultiCallGenericScheme.tsx, src/components/Proposal/RedemptionsString.tsx, src/components/Proposal/Voting/VoteButtons.tsx, src/components/Redemptions/RedemptionsPage.tsx, src/components/Scheme/ReputationFromToken.tsx, src/genericSchemeRegistry/index.ts, src/layouts/SidebarMenu.tsx, src/lib/schemeUtils.ts
resolves: https://github.com/daostack/alchemy/issues/2364
=> Get correct network

src/components/Proposal/Create/SchemeForms/CreateSchemeRegistrarProposal.tsx, test/integration/proposal-genericSchemeEnsPublicResolver.e2e.ts, test/integration/proposal-schemeregistrar.e2e.ts
verify schemeToAdd(plugin) params and not the plugin manager itself
=> verify schemeToAdd(plugin) params and not the plugin manager itself

src/components/Proposal/ProposalSummary/ProposalSummarySchemeRegistrar.tsx, src/components/Proposal/RedemptionsTip.tsx, src/layouts/SidebarMenu.tsx
=> more multiple network fixes

data/tokens.json
=> Whitelist Prime DAO token - fix

src/components/Proposal/Staking/StakeButtons.scss
=> Fix enable predictions button text overflows

CHANGELOG.md, package-lock.json, package.json, src/components/DaoCreator/index.tsx
=> Updated daocreator v.22

src/components/Proposal/Create/SchemeForms/Validators.ts
=> fixes #2394

CHANGELOG.md, package-lock.json, package.json
=> Update changelog for 1.0.6 release

CHANGELOG.md, src/lib/proposalHelpers.ts, src/subgraph_endpoints.json
resolves: https://github.com/daostack/alchemy/issues/2406
=> Better approach to calculate a proposal status

package-lock.json, package.json, src/components/Scheme/CL4R/CL4R.tsx, src/components/Scheme/CL4R/CL4RHelper.tsx, src/components/Scheme/CL4R/LockRow.tsx, src/components/Scheme/CL4R/PeriodRow.tsx, src/lib/util.ts
resolves: https://github.com/daostack/alchemy/issues/2414
=> A robust way to handle small REP amounts and times in CL4R scheme
